/*
 * Ported from the restaurant core (native/core/src/printing/EscPos.cpp).
 *
 * Generated by scripts/port-printing-from-restaurant.mjs. Fix the restaurant
 * source and re-run rather than editing this copy, or the two drift and the
 * market till quietly loses a fix the restaurant got.
 */
#pragma once

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace market::printing {

bool isNetworkPrinter(std::string_view printerName);
bool parseNetworkPrinter(std::string_view printerName, std::string& host, int& port);
bool parseWindowsPrinter(std::string_view printerName, std::string& windowsName);
bool parseUsbRawPrinter(std::string_view printerName, std::string& devicePath);
bool parseSerialPrinter(std::string_view printerName, std::string& port, int& baud);

bool sendRawTcp(const std::string& host, int port, const std::vector<std::uint8_t>& payload,
                std::string& errorOut, int timeoutMs = 8000);
bool sendRawWindowsPrinter(const std::string& printerName, const std::vector<std::uint8_t>& payload,
                           std::string& errorOut);
bool sendRawUsbDevice(const std::string& devicePath, const std::vector<std::uint8_t>& payload,
                      std::string& errorOut);
bool sendRawSerial(const std::string& port, int baud, const std::vector<std::uint8_t>& payload,
                   std::string& errorOut);

/**
 * Sends to whatever the target names, choosing the transport from its shape:
 * `tcp:host:port`, a raw USB device path, `serial:COM3@19200`, or a Windows
 * queue name. Same order and same rules as the restaurant till.
 */
bool sendOnce(const std::string& target, const std::vector<std::uint8_t>& bytes,
              std::string& errorOut);

}  // namespace market::printing
