-- ------------------------------------------------------------- categories --
INSERT INTO menu_categories (id, name_az, name_tr, name_en, icon, accent, image, sort_order, active) VALUES
  ('cat-ff','Fast Food','Fast Food','Fast Food','utensils','#E07B39','',1,1),
  ('cat-salads-m','Salatlar','Salatalar','Salads','leafy-green','#4FA978','',2,1),
  ('cat-chicken','Toyuq Yeməkləri','Tavuk Yemekleri','Chicken','utensils','#D9A441','',3,1),
  ('cat-meat','Ət Yeməkləri','Et Yemekleri','Meat','beef','#C45A5A','',4,1),
  ('cat-sides','Qarnir','Garnitür','Sides','wheat','#E5CF9B','',5,1),
  ('cat-cold-mezze','Soyuq Məzələr','Soğuk Mezeler','Cold Mezze','salad','#6A9BC9','',6,1),
  ('cat-hot-mezze','İsti Məzələr','Sıcak Mezeler','Hot Mezze','flame','#E07B39','',7,1),
  ('cat-fruit','Meyvə','Meyve','Fruit','apple','#52C08A','',8,1),
  ('cat-mezze','Məzələr','Mezeler','Mezze','utensils','#C9A86A','',9,1),
  ('cat-cold-m','Soyuq İçkilər','Soğuk İçecekler','Cold Drinks','cup-soda','#52C08A','',10,1),
  ('cat-hot-m','İsti İçkilər','Sıcak İçecekler','Hot Drinks','coffee','#8A744A','',11,1),
  ('cat-alcohol','Alkoqollu İçkilər','Alkollü İçecekler','Alcohol','wine','#B07FC7','',12,1),
  ('cat-beer','Pivələr','Bira','Beer','beer','#D9A441','',13,1),
  ('cat-hookah','Qəlyan','Nargile','Hookah','flame','#8A744A','',14,1);

-- ------------------------------------------------------------- menu items --
INSERT INTO menu_items
  (id, category_id, sku, name_az, name_tr, name_en, description_az, description_tr, description_en,
   price_minor, cost_minor, image, prep_minutes, station, course, allergens, calories,
   popular, sort_order, created_at, updated_at)
VALUES
('itm-ff-01','cat-ff','FF-01','Club Sandwich','Club Sandwich','Club Sandwich','','','',900,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-ff-02','cat-ff','FF-02','Burger Ət','Burger Ət','Burger Ət','','','',900,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-ff-03','cat-ff','FF-03','Burger Toyuq','Burger Toyuq','Burger Toyuq','','','',700,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-ff-04','cat-ff','FF-04','Nuggets','Nuggets','Nuggets','','','',700,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-ff-05','cat-ff','FF-05','Şaurma','Şaurma','Şaurma','','','',700,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-ff-06','cat-ff','FF-06','Hotdog','Hotdog','Hotdog','','','',400,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-sa-01','cat-salads-m','SA-01','Sezar Salatı','Sezar Salatı','Sezar Salatı','','','',800,0,'',10,'cold','starter','[]',NULL,0,1,0,0),
('itm-sa-02','cat-salads-m','SA-02','Xırt-xırt Badımcan','Xırt-xırt Badımcan','Xırt-xırt Badımcan','','','',500,0,'',10,'cold','starter','[]',NULL,0,2,0,0),
('itm-sa-03','cat-salads-m','SA-03','Çoban Salatı','Çoban Salatı','Çoban Salatı','','','',400,0,'',10,'cold','starter','[]',NULL,0,3,0,0),
('itm-sa-04','cat-salads-m','SA-04','Pomidor Salatı','Pomidor Salatı','Pomidor Salatı','','','',400,0,'',10,'cold','starter','[]',NULL,0,4,0,0),
('itm-ty-01','cat-chicken','TY-01','Toyuq Langet','Toyuq Langet','Toyuq Langet','','','',500,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-ty-02','cat-chicken','TY-02','Toyuq Qulyaj','Toyuq Qulyaj','Toyuq Qulyaj','','','',700,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-ty-03','cat-chicken','TY-03','Tabaka Broiler','Tabaka Broiler','Tabaka Broiler','','','',2000,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-ty-04','cat-chicken','TY-04','Tabaka Çolpa','Tabaka Çolpa','Tabaka Çolpa','','','',2200,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-ty-05','cat-chicken','TY-05','Çolpa Çığırtma','Çolpa Çığırtma','Çolpa Çığırtma','','','',2000,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-ty-06','cat-chicken','TY-06','Çolpa Limon Sousla','Çolpa Limon Sousla','Çolpa Limon Sousla','','','',1300,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-ty-07','cat-chicken','TY-07','Fajitos Toyuq','Fajitos Toyuq','Fajitos Toyuq','','','',900,0,'',10,'kitchen','main','[]',NULL,0,7,0,0),
('itm-ty-08','cat-chicken','TY-08','Qaymaqlı Toyuq','Qaymaqlı Toyuq','Qaymaqlı Toyuq','','','',800,0,'',10,'kitchen','main','[]',NULL,0,8,0,0),
('itm-ty-09','cat-chicken','TY-09','Şabalıdlı Çolpa','Şabalıdlı Çolpa','Şabalıdlı Çolpa','','','',2000,0,'',10,'kitchen','main','[]',NULL,0,9,0,0),
('itm-ty-10','cat-chicken','TY-10','Kiyev Kotleti','Kiyev Kotleti','Kiyev Kotleti','','','',700,0,'',10,'kitchen','main','[]',NULL,0,10,0,0),
('itm-ty-11','cat-chicken','TY-11','Toyuq Sote','Toyuq Sote','Toyuq Sote','','','',800,0,'',10,'kitchen','main','[]',NULL,0,11,0,0),
('itm-et-01','cat-meat','ET-01','Monastr Sayağı Ət','Monastr Sayağı Ət','Monastr Sayağı Ət','','','',1200,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-et-02','cat-meat','ET-02','Ət Langeti','Ət Langeti','Ət Langeti','','','',900,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-et-03','cat-meat','ET-03','Qaymaqlı Can Əti','Qaymaqlı Can Əti','Qaymaqlı Can Əti','','','',1200,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-et-04','cat-meat','ET-04','Alballı Can Əti','Alballı Can Əti','Alballı Can Əti','','','',1200,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-et-05','cat-meat','ET-05','Can Əti Qovurma','Can Əti Qovurma','Can Əti Qovurma','','','',1200,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-et-06','cat-meat','ET-06','Ət Sote','Ət Sote','Ət Sote','','','',1200,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-qn-01','cat-sides','QN-01','Düyü','Düyü','Düyü','','','',300,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-qn-02','cat-sides','QN-02','Qarabaşaq','Qarabaşaq','Qarabaşaq','','','',300,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-qn-03','cat-sides','QN-03','Spagetti','Spagetti','Spagetti','','','',300,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-qn-04','cat-sides','QN-04','Kartof Fri','Kartof Fri','Kartof Fri','','','',300,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-qn-05','cat-sides','QN-05','Kartof Ev Sayağı','Kartof Ev Sayağı','Kartof Ev Sayağı','','','',350,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-qn-06','cat-sides','QN-06','Soyutma Kartof','Soyutma Kartof','Soyutma Kartof','','','',250,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-sm-01','cat-cold-mezze','SM-01','Pendir','Pendir','Pendir','','','',300,0,'',10,'cold','starter','[]',NULL,0,1,0,0),
('itm-sm-02','cat-cold-mezze','SM-02','Turşu','Turşu','Turşu','','','',300,0,'',10,'cold','starter','[]',NULL,0,2,0,0),
('itm-sm-03','cat-cold-mezze','SM-03','Süzmə','Süzmə','Süzmə','','','',250,0,'',10,'cold','starter','[]',NULL,0,3,0,0),
('itm-sm-04','cat-cold-mezze','SM-04','Acika','Acika','Acika','','','',200,0,'',10,'cold','starter','[]',NULL,0,4,0,0),
('itm-sm-05','cat-cold-mezze','SM-05','Qatıq','Qatıq','Qatıq','','','',100,0,'',10,'cold','starter','[]',NULL,0,5,0,0),
('itm-sm-06','cat-cold-mezze','SM-06','Yaşıl Zeytun','Yaşıl Zeytun','Yaşıl Zeytun','','','',300,0,'',10,'cold','starter','[]',NULL,0,6,0,0),
('itm-sm-07','cat-cold-mezze','SM-07','Təzə Salat','Təzə Salat','Təzə Salat','','','',300,0,'',10,'cold','starter','[]',NULL,0,7,0,0),
('itm-sm-08','cat-cold-mezze','SM-08','Göyərti','Göyərti','Göyərti','','','',200,0,'',10,'cold','starter','[]',NULL,0,8,0,0),
('itm-sm-09','cat-cold-mezze','SM-09','Limon','Limon','Limon','','','',100,0,'',10,'cold','starter','[]',NULL,0,9,0,0),
('itm-im-01','cat-hot-mezze','IM-01','Yumurta Pomidor Pendirli','Yumurta Pomidor Pendirli','Yumurta Pomidor Pendirli','','','',500,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-im-02','cat-hot-mezze','IM-02','Yumurta Pomidor','Yumurta Pomidor','Yumurta Pomidor','','','',400,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-im-03','cat-hot-mezze','IM-03','Sordelka Gürcü','Sordelka Gürcü','Sordelka Gürcü','','','',500,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-im-04','cat-hot-mezze','IM-04','İveriya Sosiska Gürcü','İveriya Sosiska Gürcü','İveriya Sosiska Gürcü','','','',500,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-im-05','cat-hot-mezze','IM-05','Krakov Kolbosa Pomidorlu Pendirli','Krakov Kolbosa Pomidorlu Pendirli','Krakov Kolbosa Pomidorlu Pendirli','','','',700,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-im-06','cat-hot-mezze','IM-06','Selyodka Kartof ilə','Selyodka Kartof ilə','Selyodka Kartof ilə','','','',700,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-im-07','cat-hot-mezze','IM-07','Sosiska Manqal','Sosiska Manqal','Sosiska Manqal','','','',500,0,'',10,'kitchen','main','[]',NULL,0,7,0,0),
('itm-my-01','cat-fruit','MY-01','Meyvə Assorti','Meyvə Assorti','Meyvə Assorti','','','',1500,0,'',10,'cold','main','[]',NULL,0,1,0,0),
('itm-mz-01','cat-mezze','MZ-01','Saçaq Pendir Sadə','Saçaq Pendir Sadə','Saçaq Pendir Sadə','','','',350,0,'',10,'kitchen','main','[]',NULL,0,1,0,0),
('itm-mz-02','cat-mezze','MZ-02','Saçaq Pendir Qızartma','Saçaq Pendir Qızartma','Saçaq Pendir Qızartma','','','',400,0,'',10,'kitchen','main','[]',NULL,0,2,0,0),
('itm-mz-03','cat-mezze','MZ-03','Noxud','Noxud','Noxud','','','',250,0,'',10,'kitchen','main','[]',NULL,0,3,0,0),
('itm-mz-04','cat-mezze','MZ-04','Noxud Qızartma','Noxud Qızartma','Noxud Qızartma','','','',300,0,'',10,'kitchen','main','[]',NULL,0,4,0,0),
('itm-mz-05','cat-mezze','MZ-05','Püstə','Püstə','Püstə','','','',700,0,'',10,'kitchen','main','[]',NULL,0,5,0,0),
('itm-mz-06','cat-mezze','MZ-06','Suxari','Suxari','Suxari','','','',200,0,'',10,'kitchen','main','[]',NULL,0,6,0,0),
('itm-mz-07','cat-mezze','MZ-07','Çips','Çips','Çips','','','',300,0,'',10,'kitchen','main','[]',NULL,0,7,0,0),
('itm-mz-08','cat-mezze','MZ-08','Fimi Pendirli','Fimi Pendirli','Fimi Pendirli','','','',500,0,'',10,'kitchen','main','[]',NULL,0,8,0,0),
('itm-mz-09','cat-mezze','MZ-09','Düşbərə Qızartma','Düşbərə Qızartma','Düşbərə Qızartma','','','',400,0,'',10,'kitchen','main','[]',NULL,0,9,0,0),
('itm-mz-10','cat-mezze','MZ-10','Patanə Qızartma','Patanə Qızartma','Patanə Qızartma','','','',450,0,'',10,'kitchen','main','[]',NULL,0,10,0,0),
('itm-mz-11','cat-mezze','MZ-11','Patanə Souslu Qızartma','Patanə Souslu Qızartma','Patanə Souslu Qızartma','','','',550,0,'',10,'kitchen','main','[]',NULL,0,11,0,0),
('itm-mz-12','cat-mezze','MZ-12','Boğaz Qızartma','Boğaz Qızartma','Boğaz Qızartma','','','',400,0,'',10,'kitchen','main','[]',NULL,0,12,0,0),
('itm-mz-13','cat-mezze','MZ-13','Boğaz Hisə Verilmiş','Boğaz Hisə Verilmiş','Boğaz Hisə Verilmiş','','','',400,0,'',10,'kitchen','main','[]',NULL,0,13,0,0),
('itm-mz-14','cat-mezze','MZ-14','Boğaz Qızartma Sousda','Boğaz Qızartma Sousda','Boğaz Qızartma Sousda','','','',450,0,'',10,'kitchen','main','[]',NULL,0,14,0,0),
('itm-mz-15','cat-mezze','MZ-15','Göbələk Papaqları Pendirli','Göbələk Papaqları Pendirli','Göbələk Papaqları Pendirli','','','',500,0,'',10,'kitchen','main','[]',NULL,0,15,0,0),
('itm-mz-16','cat-mezze','MZ-16','Göbələk Suxaridə','Göbələk Suxaridə','Göbələk Suxaridə','','','',600,0,'',10,'kitchen','main','[]',NULL,0,16,0,0),
('itm-mz-17','cat-mezze','MZ-17','Qrenki Sadə','Qrenki Sadə','Qrenki Sadə','','','',400,0,'',10,'kitchen','main','[]',NULL,0,17,0,0),
('itm-mz-18','cat-mezze','MZ-18','Qrenki Pendirli','Qrenki Pendirli','Qrenki Pendirli','','','',500,0,'',10,'kitchen','main','[]',NULL,0,18,0,0),
('itm-mz-19','cat-mezze','MZ-19','Toyuq Qanadları Bufalo','Toyuq Qanadları Bufalo','Toyuq Qanadları Bufalo','','','',700,0,'',10,'kitchen','main','[]',NULL,0,19,0,0),
('itm-mz-20','cat-mezze','MZ-20','Toyuq Qanadları Suxaridə','Toyuq Qanadları Suxaridə','Toyuq Qanadları Suxaridə','','','',600,0,'',10,'kitchen','main','[]',NULL,0,20,0,0),
('itm-mz-21','cat-mezze','MZ-21','Hamsi Balıq Suxaridə','Hamsi Balıq Suxaridə','Hamsi Balıq Suxaridə','','','',500,0,'',10,'kitchen','main','[]',NULL,0,21,0,0),
('itm-mz-22','cat-mezze','MZ-22','Krivetka Dəniz','Krivetka Dəniz','Krivetka Dəniz','','','',1000,0,'',10,'kitchen','main','[]',NULL,0,22,0,0),
('itm-mz-23','cat-mezze','MZ-23','Krivetka Çay','Krivetka Çay','Krivetka Çay','','','',1000,0,'',10,'kitchen','main','[]',NULL,0,23,0,0),
('itm-mz-24','cat-mezze','MZ-24','Pendirli Kartof Fri','Pendirli Kartof Fri','Pendirli Kartof Fri','','','',500,0,'',10,'kitchen','main','[]',NULL,0,24,0,0),
('itm-mz-25','cat-mezze','MZ-25','Göbələk Çips','Göbələk Çips','Göbələk Çips','','','',500,0,'',10,'kitchen','main','[]',NULL,0,25,0,0),
('itm-mz-26','cat-mezze','MZ-26','Pendir Çubuqları','Pendir Çubuqları','Pendir Çubuqları','','','',500,0,'',10,'kitchen','main','[]',NULL,0,26,0,0),
('itm-mz-27','cat-mezze','MZ-27','Gürcü Qızartma','Gürcü Qızartma','Gürcü Qızartma','','','',120,0,'',10,'kitchen','main','[]',NULL,0,27,0,0),
('itm-mz-28','cat-mezze','MZ-28','Gürzə Qızartma','Gürzə Qızartma','Gürzə Qızartma','','','',500,0,'',10,'kitchen','main','[]',NULL,0,28,0,0),
('itm-mz-29','cat-mezze','MZ-29','Toyuq Çips','Toyuq Çips','Toyuq Çips','','','',600,0,'',10,'kitchen','main','[]',NULL,0,29,0,0),
('itm-mz-30','cat-mezze','MZ-30','Toyuq Popcorn','Toyuq Popcorn','Toyuq Popcorn','','','',500,0,'',10,'kitchen','main','[]',NULL,0,30,0,0),
('itm-mz-31','cat-mezze','MZ-31','Bildirçin','Bildirçin','Bildirçin','','','',400,0,'',10,'kitchen','main','[]',NULL,0,31,0,0),
('itm-si-01','cat-cold-m','SI-01','Coca-Cola (Banka)','Coca-Cola (Banka)','Coca-Cola (Banka)','','','',300,0,'',10,'bar','drinks','[]',NULL,0,1,0,0),
('itm-si-02','cat-cold-m','SI-02','Fuse Tea (Banka)','Fuse Tea (Banka)','Fuse Tea (Banka)','','','',300,0,'',10,'bar','drinks','[]',NULL,0,2,0,0),
('itm-si-03','cat-cold-m','SI-03','Hell','Hell','Hell','','','',250,0,'',10,'bar','drinks','[]',NULL,0,3,0,0),
('itm-si-04','cat-cold-m','SI-04','Bizon','Bizon','Bizon','','','',200,0,'',10,'bar','drinks','[]',NULL,0,4,0,0),
('itm-si-05','cat-cold-m','SI-05','Sirab Qazlı (Şüşə)','Sirab Qazlı (Şüşə)','Sirab Qazlı (Şüşə)','','','',250,0,'',10,'bar','drinks','[]',NULL,0,5,0,0),
('itm-si-06','cat-cold-m','SI-06','Sirab Qazsız (Şüşə)','Sirab Qazsız (Şüşə)','Sirab Qazsız (Şüşə)','','','',250,0,'',10,'bar','drinks','[]',NULL,0,6,0,0),
('itm-si-07','cat-cold-m','SI-07','Sarıkız','Sarıkız','Sarıkız','','','',200,0,'',10,'bar','drinks','[]',NULL,0,7,0,0),
('itm-si-08','cat-cold-m','SI-08','Power','Power','Power','','','',200,0,'',10,'bar','drinks','[]',NULL,0,8,0,0),
('itm-si-09','cat-cold-m','SI-09','Meyvə Şirəsi','Meyvə Şirəsi','Meyvə Şirəsi','','','',400,0,'',10,'bar','drinks','[]',NULL,0,9,0,0),
('itm-si-10','cat-cold-m','SI-10','Limonat (1L)','Limonat (1L)','Limonat (1L)','','','',300,0,'',10,'bar','drinks','[]',NULL,0,10,0,0),
('itm-si-11','cat-cold-m','SI-11','Ayran (Bakal)','Ayran (Bakal)','Ayran (Bakal)','','','',150,0,'',10,'bar','drinks','[]',NULL,0,11,0,0),
('itm-ii-01','cat-hot-m','II-01','Çay Şokolad','Çay Şokolad','Çay Şokolad','','','',800,0,'',10,'bar','drinks','[]',NULL,0,1,0,0),
('itm-ii-02','cat-hot-m','II-02','Çay Mürəbbə (kiçik)','Çay Mürəbbə (kiçik)','Çay Mürəbbə (kiçik)','','','',1000,0,'',10,'bar','drinks','[]',NULL,0,2,0,0),
('itm-ii-03','cat-hot-m','II-03','Çay Mürəbbə (böyük)','Çay Mürəbbə (böyük)','Çay Mürəbbə (böyük)','','','',1200,0,'',10,'bar','drinks','[]',NULL,0,3,0,0),
('itm-ii-04','cat-hot-m','II-04','Çay Popkek','Çay Popkek','Çay Popkek','','','',900,0,'',10,'bar','drinks','[]',NULL,0,4,0,0),
('itm-ii-05','cat-hot-m','II-05','Çay Paxlava','Çay Paxlava','Çay Paxlava','','','',1200,0,'',10,'bar','drinks','[]',NULL,0,5,0,0),
('itm-ii-06','cat-hot-m','II-06','Çay Snickers','Çay Snickers','Çay Snickers','','','',800,0,'',10,'bar','drinks','[]',NULL,0,6,0,0),
('itm-ii-07','cat-hot-m','II-07','Çay Rulet','Çay Rulet','Çay Rulet','','','',800,0,'',10,'bar','drinks','[]',NULL,0,7,0,0),
('itm-ii-08','cat-hot-m','II-08','Çay Çərəz','Çay Çərəz','Çay Çərəz','','','',1200,0,'',10,'bar','drinks','[]',NULL,0,8,0,0),
('itm-ii-09','cat-hot-m','II-09','Çay Dəstgahı','Çay Dəstgahı','Çay Dəstgahı','','','',3000,0,'',10,'bar','drinks','[]',NULL,0,9,0,0),
('itm-ii-10','cat-hot-m','II-10','Çay Dəstgahı (Qəlyan ilə)','Çay Dəstgahı (Qəlyan ilə)','Çay Dəstgahı (Qəlyan ilə)','','','',3800,0,'',10,'bar','drinks','[]',NULL,0,10,0,0),
('itm-ii-11','cat-hot-m','II-11','Kofe','Kofe','Kofe','','','',200,0,'',10,'bar','drinks','[]',NULL,0,11,0,0),
('itm-ii-12','cat-hot-m','II-12','Cappuccino','Cappuccino','Cappuccino','','','',250,0,'',10,'bar','drinks','[]',NULL,0,12,0,0),
('itm-al-01','cat-alcohol','AL-01','Viski (Jameson)','Viski (Jameson)','Viski (Jameson)','','','',600,0,'',10,'bar','drinks','[]',NULL,0,1,0,0),
('itm-al-02','cat-alcohol','AL-02','Chivas','Chivas','Chivas','','','',700,0,'',10,'bar','drinks','[]',NULL,0,2,0,0),
('itm-al-03','cat-alcohol','AL-03','Tekila (Olmeca)','Tekila (Olmeca)','Tekila (Olmeca)','','','',600,0,'',10,'bar','drinks','[]',NULL,0,3,0,0),
('itm-pv-01','cat-beer','PV-01','NZS','NZS','NZS','','','',150,0,'',10,'bar','drinks','[]',NULL,0,1,0,0),
('itm-pv-02','cat-beer','PV-02','Xırdalan','Xırdalan','Xırdalan','','','',300,0,'',10,'bar','drinks','[]',NULL,0,2,0,0),
('itm-pv-03','cat-beer','PV-03','Xırdalan Non Filter','Xırdalan Non Filter','Xırdalan Non Filter','','','',350,0,'',10,'bar','drinks','[]',NULL,0,3,0,0),
('itm-pv-04','cat-beer','PV-04','Efes Zero','Efes Zero','Efes Zero','','','',400,0,'',10,'bar','drinks','[]',NULL,0,4,0,0),
('itm-pv-05','cat-beer','PV-05','Efes Draft','Efes Draft','Efes Draft','','','',700,0,'',10,'bar','drinks','[]',NULL,0,5,0,0),
('itm-pv-06','cat-beer','PV-06','Baltika','Baltika','Baltika','','','',400,0,'',10,'bar','drinks','[]',NULL,0,6,0,0),
('itm-pv-07','cat-beer','PV-07','Heineken','Heineken','Heineken','','','',800,0,'',10,'bar','drinks','[]',NULL,0,7,0,0),
('itm-pv-08','cat-beer','PV-08','Jägermeister','Jägermeister','Jägermeister','','','',700,0,'',10,'bar','drinks','[]',NULL,0,8,0,0),
('itm-ql-01','cat-hookah','QL-01','Saxsıda','Saxsıda','Saxsıda','','','',1500,0,'',10,'bar','drinks','[]',NULL,0,1,0,0),
('itm-ql-02','cat-hookah','QL-02','Qreyfurt','Qreyfurt','Qreyfurt','','','',2000,0,'',10,'bar','drinks','[]',NULL,0,2,0,0),
('itm-ql-03','cat-hookah','QL-03','Ananas','Ananas','Ananas','','','',2500,0,'',10,'bar','drinks','[]',NULL,0,3,0,0);

