-- ============================================================================
-- Maison Aurelia POS - initial schema (version 1)
--
-- Conventions:
--   * Every id is a TEXT UUID generated by the core.
--   * Every money column is INTEGER minor units (qəpik). Never REAL.
--   * Every timestamp is INTEGER milliseconds since the Unix epoch.
--   * Menu-facing text carries _az / _tr / _en variants; _az is authoritative.
-- ============================================================================

-- ---------------------------------------------------------------- settings --
CREATE TABLE app_settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    value_type  TEXT NOT NULL DEFAULT 'string'
                CHECK (value_type IN ('string','int','bool','json')),
    updated_at  INTEGER NOT NULL
);

-- ------------------------------------------------------- roles & security --
CREATE TABLE roles (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    rank        INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE permissions (
    id          TEXT PRIMARY KEY,
    key         TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE role_permissions (
    role_id       TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    id             TEXT PRIMARY KEY,
    code           TEXT NOT NULL UNIQUE,
    full_name      TEXT NOT NULL,
    -- PBKDF2-HMAC-SHA256; plain PINs are never stored anywhere.
    pin_hash       TEXT NOT NULL,
    primary_role_id TEXT NOT NULL REFERENCES roles(id),
    color          TEXT NOT NULL DEFAULT '#C9A86A',
    active         INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until   INTEGER,
    last_login_at  INTEGER,
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL
);

CREATE TABLE user_roles (
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE shifts (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    terminal_id         TEXT NOT NULL DEFAULT 'TERM-01',
    status              TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
    opening_float_minor INTEGER NOT NULL DEFAULT 0,
    closing_cash_minor  INTEGER,
    expected_cash_minor INTEGER,
    variance_minor      INTEGER,
    opened_at           INTEGER NOT NULL,
    closed_at           INTEGER
);

-- Only one shift may be open per terminal at a time.
CREATE UNIQUE INDEX idx_shifts_one_open
    ON shifts(terminal_id) WHERE status = 'open';

-- ------------------------------------------------------------- floor plan --
CREATE TABLE restaurant_areas (
    id         TEXT PRIMARY KEY,
    name_az    TEXT NOT NULL,
    name_tr    TEXT NOT NULL DEFAULT '',
    name_en    TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active     INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1))
);

CREATE TABLE restaurant_tables (
    id           TEXT PRIMARY KEY,
    area_id      TEXT NOT NULL REFERENCES restaurant_areas(id),
    label        TEXT NOT NULL,
    seats        INTEGER NOT NULL DEFAULT 2,
    status       TEXT NOT NULL DEFAULT 'available'
                 CHECK (status IN ('available','occupied','reserved','waiting','ordering',
                                   'preparing','ready','payment_requested','cleaning')),
    -- Grid coordinates for the floor plan.
    pos_x        INTEGER NOT NULL DEFAULT 0,
    pos_y        INTEGER NOT NULL DEFAULT 0,
    width        INTEGER NOT NULL DEFAULT 1,
    height       INTEGER NOT NULL DEFAULT 1,
    shape        TEXT NOT NULL DEFAULT 'square' CHECK (shape IN ('square','round','booth','bar')),
    -- Set while a table is merged into another table's order.
    merged_into_id TEXT REFERENCES restaurant_tables(id),
    sort_order   INTEGER NOT NULL DEFAULT 0,
    active       INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
    updated_at   INTEGER NOT NULL
);

CREATE INDEX idx_tables_area ON restaurant_tables(area_id);
CREATE INDEX idx_tables_status ON restaurant_tables(status);

-- ------------------------------------------------------------------- menu --
CREATE TABLE menu_categories (
    id         TEXT PRIMARY KEY,
    name_az    TEXT NOT NULL,
    name_tr    TEXT NOT NULL DEFAULT '',
    name_en    TEXT NOT NULL DEFAULT '',
    icon       TEXT NOT NULL DEFAULT 'utensils',
    accent     TEXT NOT NULL DEFAULT '#C9A86A',
    image      TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active     INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1))
);

CREATE TABLE menu_items (
    id             TEXT PRIMARY KEY,
    category_id    TEXT NOT NULL REFERENCES menu_categories(id),
    sku            TEXT NOT NULL UNIQUE,
    name_az        TEXT NOT NULL,
    name_tr        TEXT NOT NULL DEFAULT '',
    name_en        TEXT NOT NULL DEFAULT '',
    description_az TEXT NOT NULL DEFAULT '',
    description_tr TEXT NOT NULL DEFAULT '',
    description_en TEXT NOT NULL DEFAULT '',
    price_minor    INTEGER NOT NULL CHECK (price_minor >= 0),
    cost_minor     INTEGER NOT NULL DEFAULT 0,
    image          TEXT NOT NULL DEFAULT '',
    prep_minutes   INTEGER NOT NULL DEFAULT 10,
    station        TEXT NOT NULL DEFAULT 'kitchen'
                   CHECK (station IN ('kitchen','grill','cold','pastry','bar')),
    course         TEXT NOT NULL DEFAULT 'main'
                   CHECK (course IN ('starter','main','dessert','drinks')),
    allergens      TEXT NOT NULL DEFAULT '[]',
    calories       INTEGER,
    popular        INTEGER NOT NULL DEFAULT 0 CHECK (popular IN (0,1)),
    available      INTEGER NOT NULL DEFAULT 1 CHECK (available IN (0,1)),
    sold_out       INTEGER NOT NULL DEFAULT 0 CHECK (sold_out IN (0,1)),
    sort_order     INTEGER NOT NULL DEFAULT 0,
    active         INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL
);

CREATE INDEX idx_items_category ON menu_items(category_id);
CREATE INDEX idx_items_available ON menu_items(available, active);

CREATE TABLE modifier_groups (
    id           TEXT PRIMARY KEY,
    name_az      TEXT NOT NULL,
    name_tr      TEXT NOT NULL DEFAULT '',
    name_en      TEXT NOT NULL DEFAULT '',
    min_select   INTEGER NOT NULL DEFAULT 0,
    max_select   INTEGER NOT NULL DEFAULT 1,
    required     INTEGER NOT NULL DEFAULT 0 CHECK (required IN (0,1)),
    multi_select INTEGER NOT NULL DEFAULT 0 CHECK (multi_select IN (0,1)),
    sort_order   INTEGER NOT NULL DEFAULT 0,
    CHECK (max_select >= min_select)
);

CREATE TABLE modifiers (
    id                TEXT PRIMARY KEY,
    group_id          TEXT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
    name_az           TEXT NOT NULL,
    name_tr           TEXT NOT NULL DEFAULT '',
    name_en           TEXT NOT NULL DEFAULT '',
    price_delta_minor INTEGER NOT NULL DEFAULT 0,
    is_default        INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)),
    available         INTEGER NOT NULL DEFAULT 1 CHECK (available IN (0,1)),
    sort_order        INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_modifiers_group ON modifiers(group_id);

CREATE TABLE menu_item_modifier_groups (
    item_id    TEXT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
    group_id   TEXT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (item_id, group_id)
);

-- ----------------------------------------------------------------- orders --
CREATE TABLE orders (
    id              TEXT PRIMARY KEY,
    order_number    TEXT NOT NULL UNIQUE,
    table_id        TEXT REFERENCES restaurant_tables(id),
    user_id         TEXT NOT NULL REFERENCES users(id),
    shift_id        TEXT REFERENCES shifts(id),
    status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','open','sent','partially_paid','paid','closed','voided')),
    guest_count     INTEGER NOT NULL DEFAULT 1,

    subtotal_minor  INTEGER NOT NULL DEFAULT 0,
    discount_minor  INTEGER NOT NULL DEFAULT 0,
    tax_minor       INTEGER NOT NULL DEFAULT 0,
    service_minor   INTEGER NOT NULL DEFAULT 0,
    total_minor     INTEGER NOT NULL DEFAULT 0,
    paid_minor      INTEGER NOT NULL DEFAULT 0,
    tip_minor       INTEGER NOT NULL DEFAULT 0,

    discount_type   TEXT CHECK (discount_type IN ('percent','amount','complimentary')),
    discount_value  INTEGER NOT NULL DEFAULT 0,
    discount_reason TEXT NOT NULL DEFAULT '',
    discount_by     TEXT REFERENCES users(id),

    note            TEXT NOT NULL DEFAULT '',
    void_reason     TEXT NOT NULL DEFAULT '',

    -- Second line of defence against duplicate submits, independent of the
    -- idempotency_keys table.
    idempotency_key TEXT UNIQUE,

    opened_at       INTEGER NOT NULL,
    submitted_at    INTEGER,
    closed_at       INTEGER,
    updated_at      INTEGER NOT NULL,

    CHECK (total_minor >= 0),
    CHECK (paid_minor >= 0)
);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_table ON orders(table_id);
CREATE INDEX idx_orders_opened ON orders(opened_at);
CREATE INDEX idx_orders_shift ON orders(shift_id);

-- A table can hold at most one live order at a time.
CREATE UNIQUE INDEX idx_orders_one_open_per_table
    ON orders(table_id)
    WHERE status IN ('draft','open','sent','partially_paid') AND table_id IS NOT NULL;

CREATE TABLE order_items (
    id                TEXT PRIMARY KEY,
    order_id          TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id        TEXT NOT NULL REFERENCES menu_items(id),
    line_seq          INTEGER NOT NULL,
    -- Snapshots: the menu may change price or name after the order is taken,
    -- but a printed bill must never retroactively change.
    name_snapshot     TEXT NOT NULL,
    unit_price_minor  INTEGER NOT NULL,
    quantity          INTEGER NOT NULL CHECK (quantity > 0),
    modifier_total_minor INTEGER NOT NULL DEFAULT 0,
    line_total_minor  INTEGER NOT NULL,
    status            TEXT NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','sent','preparing','ready','served','voided','held')),
    seat              INTEGER,
    course            TEXT CHECK (course IN ('starter','main','dessert','drinks')),
    note              TEXT NOT NULL DEFAULT '',
    held              INTEGER NOT NULL DEFAULT 0 CHECK (held IN (0,1)),
    complimentary     INTEGER NOT NULL DEFAULT 0 CHECK (complimentary IN (0,1)),
    void_reason       TEXT NOT NULL DEFAULT '',
    voided_by         TEXT REFERENCES users(id),
    sent_at           INTEGER,
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,

    UNIQUE (order_id, line_seq)
);

CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_status ON order_items(status);

CREATE TABLE order_item_modifiers (
    id                TEXT PRIMARY KEY,
    order_item_id     TEXT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    modifier_id       TEXT NOT NULL REFERENCES modifiers(id),
    group_name_snapshot TEXT NOT NULL DEFAULT '',
    name_snapshot     TEXT NOT NULL,
    price_delta_minor INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_item_modifiers_item ON order_item_modifiers(order_item_id);

CREATE TABLE order_events (
    id             TEXT PRIMARY KEY,
    order_id       TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    event          TEXT NOT NULL,
    actor_user_id  TEXT REFERENCES users(id),
    data           TEXT NOT NULL DEFAULT '{}',
    created_at     INTEGER NOT NULL
);

CREATE INDEX idx_order_events_order ON order_events(order_id, created_at);

-- -------------------------------------------------------- kitchen display --
CREATE TABLE kitchen_jobs (
    id            TEXT PRIMARY KEY,
    order_id      TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    order_item_id TEXT REFERENCES order_items(id) ON DELETE CASCADE,
    station       TEXT NOT NULL DEFAULT 'kitchen',
    status        TEXT NOT NULL DEFAULT 'new'
                  CHECK (status IN ('new','accepted','preparing','ready','completed')),
    priority      INTEGER NOT NULL DEFAULT 0,
    course        TEXT,
    created_at    INTEGER NOT NULL,
    accepted_at   INTEGER,
    ready_at      INTEGER,
    completed_at  INTEGER,
    -- Minutes after which the KDS flags this ticket as late.
    target_minutes INTEGER NOT NULL DEFAULT 15
);

CREATE INDEX idx_kitchen_status ON kitchen_jobs(status, created_at);
CREATE INDEX idx_kitchen_order ON kitchen_jobs(order_id);

-- --------------------------------------------------------------- payments --
CREATE TABLE payments (
    id                TEXT PRIMARY KEY,
    order_id          TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    method            TEXT NOT NULL CHECK (method IN ('cash','card','mixed','complimentary')),
    status            TEXT NOT NULL DEFAULT 'created'
                      CHECK (status IN ('created','waiting_for_terminal','processing','approved',
                                        'declined','canceled','unknown','refunded')),
    amount_minor      INTEGER NOT NULL CHECK (amount_minor >= 0),
    tip_minor         INTEGER NOT NULL DEFAULT 0,
    tendered_minor    INTEGER NOT NULL DEFAULT 0,
    change_minor      INTEGER NOT NULL DEFAULT 0,
    -- Set for split-by-person payments.
    seat              INTEGER,
    terminal_ref      TEXT NOT NULL DEFAULT '',
    card_last4        TEXT NOT NULL DEFAULT '',
    parent_payment_id TEXT REFERENCES payments(id),
    idempotency_key   TEXT UNIQUE,
    attempt           INTEGER NOT NULL DEFAULT 0,
    resolved_by       TEXT REFERENCES users(id),
    resolution_note   TEXT NOT NULL DEFAULT '',
    user_id           TEXT NOT NULL REFERENCES users(id),
    shift_id          TEXT REFERENCES shifts(id),
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    -- Deadline after which the mock/real terminal call is considered unknown.
    expires_at        INTEGER
);

CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_status ON payments(status);

CREATE TABLE payment_events (
    id            TEXT PRIMARY KEY,
    payment_id    TEXT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    from_state    TEXT NOT NULL,
    to_state      TEXT NOT NULL,
    reason        TEXT NOT NULL DEFAULT '',
    actor_user_id TEXT REFERENCES users(id),
    terminal_ref  TEXT NOT NULL DEFAULT '',
    raw_response  TEXT NOT NULL DEFAULT '',
    created_at    INTEGER NOT NULL
);

CREATE INDEX idx_payment_events_payment ON payment_events(payment_id, created_at);

-- ------------------------------------------------------ receipts/printing --
CREATE TABLE receipts (
    id            TEXT PRIMARY KEY,
    order_id      TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL CHECK (kind IN ('kitchen_ticket','customer_receipt',
                                                'shift_report','test_page')),
    number        TEXT NOT NULL,
    content_text  TEXT NOT NULL DEFAULT '',
    content_json  TEXT NOT NULL DEFAULT '{}',
    total_minor   INTEGER NOT NULL DEFAULT 0,
    created_at    INTEGER NOT NULL
);

CREATE INDEX idx_receipts_order ON receipts(order_id);

CREATE TABLE print_jobs (
    id              TEXT PRIMARY KEY,
    order_id        TEXT REFERENCES orders(id) ON DELETE CASCADE,
    receipt_id      TEXT REFERENCES receipts(id) ON DELETE CASCADE,
    kind            TEXT NOT NULL CHECK (kind IN ('kitchen_ticket','customer_receipt',
                                                  'shift_report','test_page')),
    target_printer  TEXT NOT NULL DEFAULT 'virtual',
    status          TEXT NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued','processing','sent','failed','retrying','completed')),
    attempts        INTEGER NOT NULL DEFAULT 0,
    max_attempts    INTEGER NOT NULL DEFAULT 5,
    last_error      TEXT NOT NULL DEFAULT '',
    payload         TEXT NOT NULL DEFAULT '',
    idempotency_key TEXT UNIQUE,
    next_attempt_at INTEGER,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
);

CREATE INDEX idx_print_jobs_status ON print_jobs(status, next_attempt_at);

-- ------------------------------------------------------------- audit/sync --
CREATE TABLE audit_logs (
    id            TEXT PRIMARY KEY,
    actor_user_id TEXT REFERENCES users(id),
    action        TEXT NOT NULL,
    entity_type   TEXT NOT NULL DEFAULT '',
    entity_id     TEXT NOT NULL DEFAULT '',
    data          TEXT NOT NULL DEFAULT '{}',
    terminal_id   TEXT NOT NULL DEFAULT 'TERM-01',
    created_at    INTEGER NOT NULL
);

CREATE INDEX idx_audit_created ON audit_logs(created_at);
CREATE INDEX idx_audit_action ON audit_logs(action);

-- Audit rows are append-only: this trigger makes tampering fail loudly rather
-- than silently succeeding.
CREATE TRIGGER audit_logs_no_update
BEFORE UPDATE ON audit_logs
BEGIN
    SELECT RAISE(ABORT, 'audit_logs is append-only');
END;

CREATE TRIGGER audit_logs_no_delete
BEFORE DELETE ON audit_logs
BEGIN
    SELECT RAISE(ABORT, 'audit_logs is append-only');
END;

CREATE TABLE idempotency_keys (
    key           TEXT PRIMARY KEY,
    method        TEXT NOT NULL,
    -- sha256 of the canonicalised payload, so a reused key carrying different
    -- data is caught rather than silently replayed.
    request_hash  TEXT NOT NULL,
    status        TEXT NOT NULL CHECK (status IN ('in_progress','completed')),
    response_json TEXT,
    entity_type   TEXT NOT NULL DEFAULT '',
    entity_id     TEXT NOT NULL DEFAULT '',
    created_at    INTEGER NOT NULL,
    expires_at    INTEGER NOT NULL
);

CREATE INDEX idx_idempotency_expiry ON idempotency_keys(expires_at);

CREATE TABLE sync_outbox (
    id          TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    operation   TEXT NOT NULL CHECK (operation IN ('create','update','delete')),
    payload     TEXT NOT NULL DEFAULT '{}',
    attempts    INTEGER NOT NULL DEFAULT 0,
    last_error  TEXT NOT NULL DEFAULT '',
    created_at  INTEGER NOT NULL,
    synced_at   INTEGER
);

CREATE INDEX idx_outbox_pending ON sync_outbox(synced_at, created_at);

CREATE TABLE sync_inbox (
    id          TEXT PRIMARY KEY,
    remote_id   TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL,
    payload     TEXT NOT NULL DEFAULT '{}',
    received_at INTEGER NOT NULL,
    applied_at  INTEGER
);
