-- 020 - photographed menu drafts for upgrades
-- Products transcribed from the photographed legacy menu.
-- Prices were not supplied reliably, therefore every new row is an unpublished
-- draft. Admin may add a picture/price and publish it without affecting the
-- existing 118-item operational menu.

INSERT INTO menu_categories
  (id,name_az,name_tr,name_en,icon,accent,image,sort_order,active)
SELECT * FROM (
  SELECT 'cat-extras','Əlavələr','Ekstralar','Extras','plus','#C9A86A','',15,1
  UNION ALL
  SELECT 'cat-fish','Balıq Yeməkləri','Balık Yemekleri','Fish','fish','#6A9BC9','',16,1
) WHERE EXISTS (SELECT 1 FROM menu_categories WHERE id='cat-ff')
ON CONFLICT(id) DO UPDATE SET active=1;


WITH legacy(id,category_id,sku,name_az,name_tr,name_en,station,course,sort_order) AS (
VALUES
  ('itm-legacy-001','cat-extras','LEG-001','Acı bibər','Acı bibər','Acı bibər','bar','drinks',1),
  ('itm-legacy-002','cat-extras','LEG-002','Alça','Alça','Alça','bar','drinks',2),
  ('itm-legacy-003','cat-extras','LEG-003','Alma','Alma','Alma','bar','drinks',3),
  ('itm-legacy-004','cat-extras','LEG-004','Ayran (Bokal)','Ayran (Bokal)','Ayran (Bokal)','bar','drinks',4),
  ('itm-legacy-005','cat-extras','LEG-005','Badam','Badam','Badam','bar','drinks',5),
  ('itm-legacy-006','cat-extras','LEG-006','Barbekü sous','Barbekü sous','Barbekü sous','bar','drinks',6),
  ('itm-legacy-007','cat-extras','LEG-007','Bulyon','Bulyon','Bulyon','bar','drinks',7),
  ('itm-legacy-008','cat-extras','LEG-008','Cərəz','Cərəz','Cərəz','bar','drinks',8),
  ('itm-legacy-009','cat-extras','LEG-009','Çörək Təndir','Çörək Təndir','Çörək Təndir','bar','drinks',9),
  ('itm-legacy-010','cat-extras','LEG-010','Çörək Zavod','Çörək Zavod','Çörək Zavod','bar','drinks',10),
  ('itm-legacy-011','cat-extras','LEG-011','Fındıq','Fındıq','Fındıq','bar','drinks',11),
  ('itm-legacy-012','cat-extras','LEG-012','Füjer','Füjer','Füjer','bar','drinks',12),
  ('itm-legacy-013','cat-extras','LEG-013','Gavalı','Gavalı','Gavalı','bar','drinks',13),
  ('itm-legacy-014','cat-extras','LEG-014','Kərə yağı','Kərə yağı','Kərə yağı','bar','drinks',14),
  ('itm-legacy-015','cat-extras','LEG-015','Kivi','Kivi','Kivi','bar','drinks',15),
  ('itm-legacy-016','cat-extras','LEG-016','Kök limon suyunda','Kök limon suyunda','Kök limon suyunda','bar','drinks',16),
  ('itm-legacy-017','cat-extras','LEG-017','Lavaş','Lavaş','Lavaş','bar','drinks',17),
  ('itm-legacy-018','cat-extras','LEG-018','Mandarin','Mandarin','Mandarin','bar','drinks',18),
  ('itm-legacy-019','cat-extras','LEG-019','Marojna','Marojna','Marojna','bar','drinks',19),
  ('itm-legacy-020','cat-extras','LEG-020','Nar','Nar','Nar','bar','drinks',20),
  ('itm-legacy-021','cat-extras','LEG-021','Pivə bokalı','Pivə bokalı','Pivə bokalı','bar','drinks',21),
  ('itm-legacy-022','cat-extras','LEG-022','Pomidor','Pomidor','Pomidor','bar','drinks',22),
  ('itm-legacy-023','cat-extras','LEG-023','Portağal','Portağal','Portağal','bar','drinks',23),
  ('itm-legacy-024','cat-extras','LEG-024','Pul bibər','Pul bibər','Pul bibər','bar','drinks',24),
  ('itm-legacy-025','cat-extras','LEG-025','Qara çörək','Qara çörək','Qara çörək','bar','drinks',25),
  ('itm-legacy-026','cat-extras','LEG-026','Qatıq','Qatıq','Qatıq','bar','drinks',26),
  ('itm-legacy-027','cat-extras','LEG-027','Qırmızı soğan','Qırmızı soğan','Qırmızı soğan','bar','drinks',27),
  ('itm-legacy-028','cat-extras','LEG-028','Qoz ləpə','Qoz ləpə','Qoz ləpə','bar','drinks',28),
  ('itm-legacy-029','cat-beer','LEG-029','Baltika (0)','Baltika (0)','Baltika (0)','bar','drinks',1),
  ('itm-legacy-030','cat-beer','LEG-030','Efes (Draft)','Efes (Draft)','Efes (Draft)','bar','drinks',2),
  ('itm-legacy-031','cat-beer','LEG-031','Efes (Zero)','Efes (Zero)','Efes (Zero)','bar','drinks',3),
  ('itm-legacy-032','cat-beer','LEG-032','NZS (Bokal)','NZS (Bokal)','NZS (Bokal)','bar','drinks',4),
  ('itm-legacy-033','cat-beer','LEG-033','NZS (Füjer)','NZS (Füjer)','NZS (Füjer)','bar','drinks',5),
  ('itm-legacy-034','cat-beer','LEG-034','Tuborg','Tuborg','Tuborg','bar','drinks',6),
  ('itm-legacy-035','cat-beer','LEG-035','Xırdalan','Xırdalan','Xırdalan','bar','drinks',7),
  ('itm-legacy-036','cat-beer','LEG-036','Xırdalan (0)','Xırdalan (0)','Xırdalan (0)','bar','drinks',8),
  ('itm-legacy-037','cat-beer','LEG-037','Xırdalan Non Filter (Bokal)','Xırdalan Non Filter (Bokal)','Xırdalan Non Filter (Bokal)','bar','drinks',9),
  ('itm-legacy-038','cat-beer','LEG-038','Xırdalan Non Filter (Füjer)','Xırdalan Non Filter (Füjer)','Xırdalan Non Filter (Füjer)','bar','drinks',10),
  ('itm-legacy-039','cat-beer','LEG-039','Xırdalan Sadə (Bokal)','Xırdalan Sadə (Bokal)','Xırdalan Sadə (Bokal)','bar','drinks',11),
  ('itm-legacy-040','cat-beer','LEG-040','Xırdalan Sadə (Füjer)','Xırdalan Sadə (Füjer)','Xırdalan Sadə (Füjer)','bar','drinks',12),
  ('itm-legacy-041','cat-ff','LEG-041','Club Sandwich','Club Sandwich','Club Sandwich','kitchen','main',1),
  ('itm-legacy-042','cat-ff','LEG-042','Corey Arası Sosis','Corey Arası Sosis','Corey Arası Sosis','kitchen','main',2),
  ('itm-legacy-043','cat-ff','LEG-043','Corey Arası Sosis + Fri','Corey Arası Sosis + Fri','Corey Arası Sosis + Fri','kitchen','main',3),
  ('itm-legacy-044','cat-ff','LEG-044','Dürüm Sosis','Dürüm Sosis','Dürüm Sosis','kitchen','main',4),
  ('itm-legacy-045','cat-ff','LEG-045','Fri','Fri','Fri','kitchen','main',5),
  ('itm-legacy-046','cat-ff','LEG-046','Meksikan Naços','Meksikan Naços','Meksikan Naços','kitchen','main',6),
  ('itm-legacy-047','cat-ff','LEG-047','Naggets','Naggets','Naggets','kitchen','main',7),
  ('itm-legacy-048','cat-ff','LEG-048','Naggets + Fri','Naggets + Fri','Naggets + Fri','kitchen','main',8),
  ('itm-legacy-049','cat-ff','LEG-049','Şaurma','Şaurma','Şaurma','kitchen','main',9),
  ('itm-legacy-050','cat-ff','LEG-050','Şaurma (Milioner)','Şaurma (Milioner)','Şaurma (Milioner)','kitchen','main',10),
  ('itm-legacy-051','cat-ff','LEG-051','Şaurma + Fri','Şaurma + Fri','Şaurma + Fri','kitchen','main',11),
  ('itm-legacy-052','cat-meat','LEG-052','Can əti albalı','Can əti albalı','Can əti albalı','kitchen','main',1),
  ('itm-legacy-053','cat-meat','LEG-053','Can əti langet','Can əti langet','Can əti langet','kitchen','main',2),
  ('itm-legacy-054','cat-meat','LEG-054','Can əti nar qovurma','Can əti nar qovurma','Can əti nar qovurma','kitchen','main',3),
  ('itm-legacy-055','cat-meat','LEG-055','Can əti qovurma','Can əti qovurma','Can əti qovurma','kitchen','main',4),
  ('itm-legacy-056','cat-meat','LEG-056','Ət Langet','Ət Langet','Ət Langet','kitchen','main',5),
  ('itm-legacy-057','cat-meat','LEG-057','Ət Qulyas','Ət Qulyas','Ət Qulyas','kitchen','main',6),
  ('itm-legacy-058','cat-meat','LEG-058','Faxitos','Faxitos','Faxitos','kitchen','main',7),
  ('itm-legacy-059','cat-meat','LEG-059','Kotlet','Kotlet','Kotlet','kitchen','main',8),
  ('itm-legacy-060','cat-meat','LEG-060','Kotlet + Yumurta','Kotlet + Yumurta','Kotlet + Yumurta','kitchen','main',9),
  ('itm-legacy-061','cat-meat','LEG-061','Monastır sayağı ət','Monastır sayağı ət','Monastır sayağı ət','kitchen','main',10),
  ('itm-legacy-062','cat-meat','LEG-062','Nar qovurma','Nar qovurma','Nar qovurma','kitchen','main',11),
  ('itm-legacy-063','cat-meat','LEG-063','Qaymaqlı can əti','Qaymaqlı can əti','Qaymaqlı can əti','kitchen','main',12),
  ('itm-legacy-064','cat-meat','LEG-064','Qiymə ət bibərli','Qiymə ət bibərli','Qiymə ət bibərli','kitchen','main',13),
  ('itm-legacy-065','cat-meat','LEG-065','Qiymə ət','Qiymə ət','Qiymə ət','kitchen','main',14),
  ('itm-legacy-066','cat-meat','LEG-066','Quzu qovurma','Quzu qovurma','Quzu qovurma','kitchen','main',15),
  ('itm-legacy-067','cat-meat','LEG-067','Saç (Quzu)','Saç (Quzu)','Saç (Quzu)','kitchen','main',16),
  ('itm-legacy-068','cat-meat','LEG-068','Saç Can Əti','Saç Can Əti','Saç Can Əti','kitchen','main',17),
  ('itm-legacy-069','cat-meat','LEG-069','Sireli Dana','Sireli Dana','Sireli Dana','kitchen','main',18),
  ('itm-legacy-070','cat-meat','LEG-070','Stroqanov','Stroqanov','Stroqanov','kitchen','main',19),
  ('itm-legacy-071','cat-meat','LEG-071','Tusonka + Kartof','Tusonka + Kartof','Tusonka + Kartof','kitchen','main',20),
  ('itm-legacy-072','cat-fish','LEG-072','Dorado','Dorado','Dorado','kitchen','main',1),
  ('itm-legacy-073','cat-fish','LEG-073','Forel','Forel','Forel','kitchen','main',2),
  ('itm-legacy-074','cat-fish','LEG-074','Forel hisə verilmiş','Forel hisə verilmiş','Forel hisə verilmiş','kitchen','main',3),
  ('itm-legacy-075','cat-fish','LEG-075','Forel qızartma','Forel qızartma','Forel qızartma','kitchen','main',4),
  ('itm-legacy-076','cat-fish','LEG-076','Selyodka','Selyodka','Selyodka','kitchen','main',5),
  ('itm-legacy-077','cat-fish','LEG-077','Selyodka + Kartof','Selyodka + Kartof','Selyodka + Kartof','kitchen','main',6),
  ('itm-legacy-078','cat-fish','LEG-078','Skumbriya','Skumbriya','Skumbriya','kitchen','main',7),
  ('itm-legacy-079','cat-hot-m','LEG-079','Caska Çay','Caska Çay','Caska Çay','bar','drinks',1),
  ('itm-legacy-080','cat-hot-m','LEG-080','Çay','Çay','Çay','bar','drinks',2),
  ('itm-legacy-081','cat-hot-m','LEG-081','Çay Dəsgah','Çay Dəsgah','Çay Dəsgah','bar','drinks',3),
  ('itm-legacy-082','cat-hot-m','LEG-082','Çay Gavalı','Çay Gavalı','Çay Gavalı','bar','drinks',4),
  ('itm-legacy-083','cat-hot-m','LEG-083','Çay + Quru meyvə','Çay + Quru meyvə','Çay + Quru meyvə','bar','drinks',5),
  ('itm-legacy-084','cat-hot-m','LEG-084','Çay + Cərəz','Çay + Cərəz','Çay + Cərəz','bar','drinks',6),
  ('itm-legacy-085','cat-hot-m','LEG-085','Çay + Kişmiş','Çay + Kişmiş','Çay + Kişmiş','bar','drinks',7),
  ('itm-legacy-086','cat-hot-m','LEG-086','Çay + Mürəbbə (10)','Çay + Mürəbbə (10)','Çay + Mürəbbə (10)','bar','drinks',8),
  ('itm-legacy-087','cat-hot-m','LEG-087','Çay + Mürəbbə (12)','Çay + Mürəbbə (12)','Çay + Mürəbbə (12)','bar','drinks',9),
  ('itm-legacy-088','cat-hot-m','LEG-088','Çay + Paxlava','Çay + Paxlava','Çay + Paxlava','bar','drinks',10),
  ('itm-legacy-089','cat-hot-m','LEG-089','Çay + Plitka','Çay + Plitka','Çay + Plitka','bar','drinks',11),
  ('itm-legacy-090','cat-hot-m','LEG-090','Çay + Popkek','Çay + Popkek','Çay + Popkek','bar','drinks',12),
  ('itm-legacy-091','cat-hot-m','LEG-091','Çay + Pryanik','Çay + Pryanik','Çay + Pryanik','bar','drinks',13),
  ('itm-legacy-092','cat-hot-m','LEG-092','Çay + Snickers','Çay + Snickers','Çay + Snickers','bar','drinks',14),
  ('itm-legacy-093','cat-hot-m','LEG-093','Çay + Şokolad','Çay + Şokolad','Çay + Şokolad','bar','drinks',15),
  ('itm-legacy-094','cat-hot-m','LEG-094','Çay + Toffi','Çay + Toffi','Çay + Toffi','bar','drinks',16),
  ('itm-legacy-095','cat-hot-m','LEG-095','Çay + Xurma','Çay + Xurma','Çay + Xurma','bar','drinks',17),
  ('itm-legacy-096','cat-hot-m','LEG-096','Ətirli çay','Ətirli çay','Ətirli çay','bar','drinks',18),
  ('itm-legacy-097','cat-hot-m','LEG-097','Kapuçino','Kapuçino','Kapuçino','bar','drinks',19),
  ('itm-legacy-098','cat-hot-m','LEG-098','Kişmiş','Kişmiş','Kişmiş','bar','drinks',20),
  ('itm-legacy-099','cat-hot-m','LEG-099','Kofe','Kofe','Kofe','bar','drinks',21),
  ('itm-legacy-100','cat-hot-m','LEG-100','Mürəbbə (7)','Mürəbbə (7)','Mürəbbə (7)','bar','drinks',22),
  ('itm-legacy-101','cat-hot-m','LEG-101','Mürəbbə (9)','Mürəbbə (9)','Mürəbbə (9)','bar','drinks',23),
  ('itm-legacy-102','cat-hot-m','LEG-102','Popkek','Popkek','Popkek','bar','drinks',24),
  ('itm-legacy-103','cat-hot-m','LEG-103','Pryanik','Pryanik','Pryanik','bar','drinks',25),
  ('itm-legacy-104','cat-hot-m','LEG-104','Quru meyvə + Çay','Quru meyvə + Çay','Quru meyvə + Çay','bar','drinks',26),
  ('itm-legacy-105','cat-hot-m','LEG-105','Samovar','Samovar','Samovar','bar','drinks',27),
  ('itm-legacy-106','cat-hot-m','LEG-106','Şokolad','Şokolad','Şokolad','bar','drinks',28),
  ('itm-legacy-107','cat-mezze','LEG-107','Araxıs','Araxıs','Araxıs','kitchen','starter',1),
  ('itm-legacy-108','cat-mezze','LEG-108','Badımcan Cipsi','Badımcan Cipsi','Badımcan Cipsi','kitchen','starter',2),
  ('itm-legacy-109','cat-mezze','LEG-109','Basdırma Ət','Basdırma Ət','Basdırma Ət','kitchen','starter',3),
  ('itm-legacy-110','cat-mezze','LEG-110','Bildirçin','Bildirçin','Bildirçin','kitchen','starter',4),
  ('itm-legacy-111','cat-mezze','LEG-111','Boğaz Hisə Verilmiş','Boğaz Hisə Verilmiş','Boğaz Hisə Verilmiş','kitchen','starter',5),
  ('itm-legacy-112','cat-mezze','LEG-112','Boğaz Qızartma','Boğaz Qızartma','Boğaz Qızartma','kitchen','starter',6),
  ('itm-legacy-113','cat-mezze','LEG-113','Boğaz Qızartma Barbekü Souslu','Boğaz Qızartma Barbekü Souslu','Boğaz Qızartma Barbekü Souslu','kitchen','starter',7),
  ('itm-legacy-114','cat-mezze','LEG-114','Boğaz Turşulu','Boğaz Turşulu','Boğaz Turşulu','kitchen','starter',8),
  ('itm-legacy-115','cat-mezze','LEG-115','Cipsi','Cipsi','Cipsi','kitchen','starter',9),
  ('itm-legacy-116','cat-mezze','LEG-116','Düşbərə Qızartma','Düşbərə Qızartma','Düşbərə Qızartma','kitchen','starter',10),
  ('itm-legacy-117','cat-mezze','LEG-117','Fimi Assorti','Fimi Assorti','Fimi Assorti','kitchen','starter',11),
  ('itm-legacy-118','cat-mezze','LEG-118','Göbələk Cipsi','Göbələk Cipsi','Göbələk Cipsi','kitchen','starter',12),
  ('itm-legacy-119','cat-mezze','LEG-119','Göbələk Papaqları Pendirli','Göbələk Papaqları Pendirli','Göbələk Papaqları Pendirli','kitchen','starter',13),
  ('itm-legacy-120','cat-mezze','LEG-120','Göbələk Popkorn','Göbələk Popkorn','Göbələk Popkorn','kitchen','starter',14),
  ('itm-legacy-121','cat-mezze','LEG-121','Gürzə','Gürzə','Gürzə','kitchen','starter',15),
  ('itm-legacy-122','cat-mezze','LEG-122','Hamsi Qızartma','Hamsi Qızartma','Hamsi Qızartma','kitchen','starter',16),
  ('itm-legacy-123','cat-mezze','LEG-123','Kanapə','Kanapə','Kanapə','kitchen','starter',17),
  ('itm-legacy-124','cat-mezze','LEG-124','Krivetka (Dəniz-Çay)','Krivetka (Dəniz-Çay)','Krivetka (Dəniz-Çay)','kitchen','starter',18),
  ('itm-legacy-125','cat-mezze','LEG-125','Krivetka Tempura','Krivetka Tempura','Krivetka Tempura','kitchen','starter',19),
  ('itm-legacy-126','cat-mezze','LEG-126','Lavaş Cipsi','Lavaş Cipsi','Lavaş Cipsi','kitchen','starter',20),
  ('itm-legacy-127','cat-mezze','LEG-127','Naços','Naços','Naços','kitchen','starter',21),
  ('itm-legacy-128','cat-mezze','LEG-128','Noxud','Noxud','Noxud','kitchen','starter',22),
  ('itm-legacy-129','cat-mezze','LEG-129','Noxud Edviyyatlı','Noxud Edviyyatlı','Noxud Edviyyatlı','kitchen','starter',23),
  ('itm-legacy-130','cat-mezze','LEG-130','Noxud Qızartma','Noxud Qızartma','Noxud Qızartma','kitchen','starter',24),
  ('itm-legacy-131','cat-mezze','LEG-131','Pendir Çubuqları','Pendir Çubuqları','Pendir Çubuqları','kitchen','starter',25),
  ('itm-legacy-132','cat-mezze','LEG-132','Pendirli Fri','Pendirli Fri','Pendirli Fri','kitchen','starter',26),
  ('itm-legacy-133','cat-mezze','LEG-133','Pətənək Qızartma','Pətənək Qızartma','Pətənək Qızartma','kitchen','starter',27),
  ('itm-legacy-134','cat-mezze','LEG-134','Pətənək (Barbekü Souslu)','Pətənək (Barbekü Souslu)','Pətənək (Barbekü Souslu)','kitchen','starter',28),
  ('itm-legacy-135','cat-mezze','LEG-135','Pətənək Turşulu','Pətənək Turşulu','Pətənək Turşulu','kitchen','starter',29),
  ('itm-legacy-136','cat-mezze','LEG-136','Püstə','Püstə','Püstə','kitchen','starter',30),
  ('itm-legacy-137','cat-mezze','LEG-137','Qrenki Pendirli','Qrenki Pendirli','Qrenki Pendirli','kitchen','starter',31),
  ('itm-legacy-138','cat-mezze','LEG-138','Qutab (mini)','Qutab (mini)','Qutab (mini)','kitchen','starter',32),
  ('itm-legacy-139','cat-mezze','LEG-139','Saçaq Pendir (Ədviyyatlı)','Saçaq Pendir (Ədviyyatlı)','Saçaq Pendir (Ədviyyatlı)','kitchen','starter',33),
  ('itm-legacy-140','cat-mezze','LEG-140','Saçaq Pendir Qızartma','Saçaq Pendir Qızartma','Saçaq Pendir Qızartma','kitchen','starter',34),
  ('itm-legacy-141','cat-mezze','LEG-141','Saçaq Pendir Sadə','Saçaq Pendir Sadə','Saçaq Pendir Sadə','kitchen','starter',35),
  ('itm-legacy-142','cat-mezze','LEG-142','Suxari','Suxari','Suxari','kitchen','starter',36),
  ('itm-legacy-143','cat-mezze','LEG-143','Suxari Obertos','Suxari Obertos','Suxari Obertos','kitchen','starter',37),
  ('itm-legacy-144','cat-mezze','LEG-144','Toyuq Chersi','Toyuq Chersi','Toyuq Chersi','kitchen','starter',38),
  ('itm-legacy-145','cat-mezze','LEG-145','Toyuq Cipsi','Toyuq Cipsi','Toyuq Cipsi','kitchen','starter',39),
  ('itm-legacy-146','cat-mezze','LEG-146','Toyuq Halqaları','Toyuq Halqaları','Toyuq Halqaları','kitchen','starter',40),
  ('itm-legacy-147','cat-mezze','LEG-147','Toyuq Popkorn','Toyuq Popkorn','Toyuq Popkorn','kitchen','starter',41),
  ('itm-legacy-148','cat-mezze','LEG-148','Toyuq Qanadları Buffalo','Toyuq Qanadları Buffalo','Toyuq Qanadları Buffalo','kitchen','starter',42),
  ('itm-legacy-149','cat-mezze','LEG-149','Toyuq Qanadları Suxaridə','Toyuq Qanadları Suxaridə','Toyuq Qanadları Suxaridə','kitchen','starter',43),
  ('itm-legacy-150','cat-mezze','LEG-150','Tum (Ağ)','Tum (Ağ)','Tum (Ağ)','kitchen','starter',44),
  ('itm-legacy-151','cat-mezze','LEG-151','Tum (Qara)','Tum (Qara)','Tum (Qara)','kitchen','starter',45),
  ('itm-legacy-152','cat-mezze','LEG-152','Xəngəl Qızartma','Xəngəl Qızartma','Xəngəl Qızartma','kitchen','starter',46),
  ('itm-legacy-153','cat-mezze','LEG-153','Xırt-xırt Sosis','Xırt-xırt Sosis','Xırt-xırt Sosis','kitchen','starter',47),
  ('itm-legacy-154','cat-hot-mezze','LEG-154','İveriya','İveriya','İveriya','kitchen','starter',1),
  ('itm-legacy-155','cat-hot-mezze','LEG-155','Kartof ev sayağı yumurta','Kartof ev sayağı yumurta','Kartof ev sayağı yumurta','kitchen','starter',2),
  ('itm-legacy-156','cat-hot-mezze','LEG-156','Krakov kolbasa pendirli','Krakov kolbasa pendirli','Krakov kolbasa pendirli','kitchen','starter',3),
  ('itm-legacy-157','cat-hot-mezze','LEG-157','Pomidor yumurta','Pomidor yumurta','Pomidor yumurta','kitchen','starter',4),
  ('itm-legacy-158','cat-hot-mezze','LEG-158','Pomidor yumurta pendirli','Pomidor yumurta pendirli','Pomidor yumurta pendirli','kitchen','starter',5),
  ('itm-legacy-159','cat-hot-mezze','LEG-159','Qayğanaq (yumurta)','Qayğanaq (yumurta)','Qayğanaq (yumurta)','kitchen','starter',6),
  ('itm-legacy-160','cat-hot-mezze','LEG-160','Sardelka (Gürcü)','Sardelka (Gürcü)','Sardelka (Gürcü)','kitchen','starter',7),
  ('itm-legacy-161','cat-hot-mezze','LEG-161','Selyodka kartof','Selyodka kartof','Selyodka kartof','kitchen','starter',8),
  ('itm-legacy-162','cat-hot-mezze','LEG-162','Sosiska manqal','Sosiska manqal','Sosiska manqal','kitchen','starter',9),
  ('itm-legacy-163','cat-hot-mezze','LEG-163','Sosiska + Yumurta','Sosiska + Yumurta','Sosiska + Yumurta','kitchen','starter',10),
  ('itm-legacy-164','cat-sides','LEG-164','Düyü','Düyü','Düyü','kitchen','main',1),
  ('itm-legacy-165','cat-sides','LEG-165','Düyü + Langet','Düyü + Langet','Düyü + Langet','kitchen','main',2),
  ('itm-legacy-166','cat-sides','LEG-166','Kartof Ev Sayağı','Kartof Ev Sayağı','Kartof Ev Sayağı','kitchen','main',3),
  ('itm-legacy-167','cat-sides','LEG-167','Püre','Püre','Püre','kitchen','main',4),
  ('itm-legacy-168','cat-sides','LEG-168','Püre Yumurtalı','Püre Yumurtalı','Püre Yumurtalı','kitchen','main',5),
  ('itm-legacy-169','cat-sides','LEG-169','Qreçka','Qreçka','Qreçka','kitchen','main',6),
  ('itm-legacy-170','cat-sides','LEG-170','Soyutma Kartof','Soyutma Kartof','Soyutma Kartof','kitchen','main',7),
  ('itm-legacy-171','cat-sides','LEG-171','Spagetti','Spagetti','Spagetti','kitchen','main',8),
  ('itm-legacy-172','cat-sides','LEG-172','Spagetti Pendirli','Spagetti Pendirli','Spagetti Pendirli','kitchen','main',9),
  ('itm-legacy-173','cat-hookah','LEG-173','Qəlyan Caskada','Qəlyan Caskada','Qəlyan Caskada','bar','drinks',1),
  ('itm-legacy-174','cat-hookah','LEG-174','Qəlyan Caskada Premium','Qəlyan Caskada Premium','Qəlyan Caskada Premium','bar','drinks',2),
  ('itm-legacy-175','cat-hookah','LEG-175','Qəlyan Endirimli','Qəlyan Endirimli','Qəlyan Endirimli','bar','drinks',3),
  ('itm-legacy-176','cat-hookah','LEG-176','Qəlyan Qreyfrutda','Qəlyan Qreyfrutda','Qəlyan Qreyfrutda','bar','drinks',4)
)
INSERT INTO menu_items
  (id,category_id,sku,name_az,name_tr,name_en,description_az,description_tr,description_en,
   price_minor,cost_minor,image,prep_minutes,station,course,allergens,calories,popular,
   available,sold_out,sort_order,active,archived,kitchen_route,tags_json,created_at,updated_at)
SELECT l.id,l.category_id,l.sku,l.name_az,l.name_tr,l.name_en,'','','',
       0,0,'',10,l.station,l.course,'[]',NULL,0,1,0,l.sort_order,0,0,'','[]',
       CAST(strftime('%s','now') AS INTEGER)*1000,
       CAST(strftime('%s','now') AS INTEGER)*1000
FROM legacy l
WHERE EXISTS (SELECT 1 FROM menu_categories c WHERE c.id=l.category_id)
  AND NOT EXISTS (
    SELECT 1 FROM menu_items m
    WHERE m.archived=0 AND lower(trim(m.name_az))=lower(trim(l.name_az))
  );
