#include "market/printing/PrinterHandlers.hpp"

#include <chrono>
#include <string>
#include <vector>

#include "market/Error.hpp"
#include "market/RetailOps.hpp"
#include "market/printing/DeviceDiscovery.hpp"
#include "market/printing/RawSend.hpp"

namespace market::printing {
namespace {

using Json = nlohmann::json;

/** Monotonic, for probe durations only - never for a stored timestamp. */
std::int64_t elapsedMs() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::steady_clock::now().time_since_epoch())
        .count();
}

/**
 * An audit row. The id and the timestamp are generated by sqlite rather than
 * borrowed from RetailOps.cpp, whose helpers are file-local.
 */
void auditPrinter(db::Database& db, const std::string& actorId, const std::string& action,
                  const std::string& detail) {
    sqlite3_stmt* stmt = nullptr;
    sqlite3_prepare_v2(db.raw(),
                       "INSERT INTO audit_logs(id, created_at, actor_id, action, detail) "
                       "VALUES ('audit_' || lower(hex(randomblob(8))), "
                       "        CAST(strftime('%s','now') AS INTEGER) * 1000, ?, ?, ?)",
                       -1, &stmt, nullptr);
    sqlite3_bind_text(stmt, 1, actorId.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 2, action.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_bind_text(stmt, 3, detail.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);
}

Json printerConfig(db::Database& db) {
    const auto raw = db.queryText("SELECT value FROM settings WHERE key = 'printerConfig'");
    if (raw.empty()) return Json::object();
    try {
        auto parsed = Json::parse(raw);
        return parsed.is_object() ? parsed : Json::object();
    } catch (...) {
        return Json::object();
    }
}

/** The configured destination, empty when the till has never chosen one. */
std::string currentTarget(db::Database& db) {
    const auto config = printerConfig(db);
    const auto target = config.value("target", std::string{});
    return target == "auto" ? std::string{} : target;
}

void rememberTarget(db::Database& db, const std::string& target) {
    auto config = printerConfig(db);
    config["target"] = target;
    const auto value = config.dump();

    sqlite3_stmt* stmt = nullptr;
    sqlite3_prepare_v2(db.raw(),
                       "INSERT INTO settings(key, value) VALUES ('printerConfig', ?) "
                       "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                       -1, &stmt, nullptr);
    sqlite3_bind_text(stmt, 1, value.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);
}

/**
 * A short page proving the device is real and prints legibly.
 *
 * Deliberately not a blank feed: detection picks the first candidate that
 * accepts bytes, and a spooler queue pointed at a PDF accepts them happily.
 * The operator looking at the counter is the last check, so the page has to
 * say which of the candidates printed it.
 */
std::vector<std::uint8_t> probePage(const std::string& label) {
    std::vector<std::uint8_t> out{0x1B, 0x40, 0x1B, 0x61, 0x01};  // init, centre
    const std::string text = "AptekPos\nPRINTER TESTI\n\n" + label + "\n\n";
    out.insert(out.end(), text.begin(), text.end());
    out.insert(out.end(), {0x1B, 0x64, 0x04});  // feed 4
    out.insert(out.end(), {0x1D, 0x56, 0x00});  // full cut
    return out;
}

/** A candidate in the shape the settings screen consumes. */
Json candidateToJson(const PrinterCandidate& candidate) {
    std::string model = candidate.model;
    if (!candidate.manufacturer.empty()) {
        model = model.empty() ? candidate.manufacturer : candidate.manufacturer + " " + model;
    }
    const auto status = decodeEscPosStatus(candidate.statusByte);

    return Json{{"target", candidate.target},
                {"displayName", candidate.displayName},
                {"connection", std::string(linkToString(candidate.link))},
                {"model", model},
                {"commandSet", candidate.commandSet},
                {"vendorId", candidate.vendorId},
                {"productId", candidate.productId},
                {"port", candidate.port},
                {"driver", candidate.driver},
                {"ipAddress", candidate.ipAddress},
                {"macAddress", candidate.macAddress},
                {"escposConfirmed", candidate.escposConfirmed},
                {"score", candidate.score},
                {"isCurrent", candidate.isCurrent},
                {"status", candidate.escposConfirmed && !status.online ? "offline" : "ready"}};
}

/** `{"bytes": [27, 64, ...]}` - a JSON array, so no encoding lives here. */
std::vector<std::uint8_t> payloadBytes(const Json& payload) {
    if (!payload.contains("bytes") || !payload["bytes"].is_array()) {
        throw PosError("E_VALIDATION", "bytes array required");
    }
    std::vector<std::uint8_t> bytes;
    bytes.reserve(payload["bytes"].size());
    for (const auto& value : payload["bytes"]) {
        if (!value.is_number_integer()) throw PosError("E_VALIDATION", "bytes must be integers");
        const auto byte = value.get<std::int64_t>();
        if (byte < 0 || byte > 255) throw PosError("E_VALIDATION", "byte out of range");
        bytes.push_back(static_cast<std::uint8_t>(byte));
    }
    if (bytes.empty()) throw PosError("E_VALIDATION", "nothing to print");
    return bytes;
}

}  // namespace

void registerPrinterHandlers(ipc::StdioServer& server, db::Database& db) {
    // Local links only. This runs whenever the settings screen opens, and a LAN
    // sweep there would make it feel broken for six seconds.
    server.on("printer.list", [&db](const Json&) {
        Json printers = Json::array();
        for (const auto& candidate : rankPrinterCandidates(currentTarget(db), false)) {
            printers.push_back(candidateToJson(candidate));
        }
        return Json{{"printers", printers}, {"current", currentTarget(db)}};
    });

    // The whole search, network included, then a real page to each candidate in
    // rank order until one takes it. The first that prints becomes the till's
    // printer - the operator gets a working printer rather than a list to read.
    server.on("printer.detect", [&db](const Json& p) {
        requirePermission(db, p, "MANAGE_SETTINGS");

        const bool probe = p.value("probe", true);
        const auto current = currentTarget(db);
        const auto candidates = rankPrinterCandidates(current, true);

        Json listed = Json::array();
        for (const auto& candidate : candidates) listed.push_back(candidateToJson(candidate));

        Json probed = Json::array();
        std::string chosen;
        if (probe) {
            for (const auto& candidate : candidates) {
                if (candidate.link == PrinterLink::Virtual) continue;
                if (candidate.score <= 0) continue;

                const auto started = elapsedMs();
                std::string error;
                const bool ok = sendOnce(candidate.target,
                                         probePage(candidate.displayName.empty() ? candidate.target
                                                                                 : candidate.displayName),
                                         error);
                probed.push_back(Json{{"target", candidate.target},
                                      {"displayName", candidate.displayName},
                                      {"ok", ok},
                                      {"error", error},
                                      {"durationMs", elapsedMs() - started}});
                if (ok) {
                    chosen = candidate.target;
                    break;
                }
            }
        }

        if (!chosen.empty()) {
            rememberTarget(db, chosen);
            auditPrinter(db, p.value("actorId", "system"), "PRINTER_AUTODETECT", chosen);
            for (auto& candidate : listed) {
                candidate["isCurrent"] = candidate.value("target", "") == chosen;
            }
        }

        return Json{{"printers", listed},
                    {"current", chosen.empty() ? current : chosen},
                    {"chosen", chosen.empty() ? Json(nullptr) : Json(chosen)},
                    {"probed", probed}};
    });

    server.on("printer.setTarget", [&db](const Json& p) {
        requirePermission(db, p, "MANAGE_SETTINGS");
        const auto target = p.value("target", std::string{});
        if (target.empty()) throw PosError("E_VALIDATION", "target required");
        rememberTarget(db, target);
        auditPrinter(db, p.value("actorId", "system"), "PRINTER_SET_TARGET", target);
        return Json{{"ok", true}, {"current", target}};
    });

    // Electron builds the ESC/POS bytes and hands them here. `target` overrides
    // the configured one so a test page can go to a printer before it is chosen.
    server.on("printer.send", [&db](const Json& p) {
        auto target = p.value("target", std::string{});
        if (target.empty()) target = currentTarget(db);
        if (target.empty()) {
            throw PosError("PRINTER_NOT_CONFIGURED",
                           "Printer seçilməyib — Parametrlərdən printeri tapın", false);
        }

        const auto bytes = payloadBytes(p);
        std::string error;
        if (!sendOnce(target, bytes, error)) {
            // Retryable: the usual cause is a printer that is off or unplugged,
            // and the till should offer the operator another go rather than
            // treating a receipt as permanently lost.
            throw PosError("PRINTER_SEND_FAILED", error.empty() ? "Printerə göndərilmədi" : error, true,
                           Json{{"target", target}});
        }
        return Json{{"ok", true}, {"target", target}, {"bytes", bytes.size()}};
    });
}

}  // namespace market::printing
