/*
 * Ported from the restaurant core (native/core/src/printing/EscPos.cpp).
 *
 * Generated by scripts/port-printing-from-restaurant.mjs. Fix the restaurant
 * source and re-run rather than editing this copy, or the two drift and the
 * market till quietly loses a fix the restaurant got.
 */
#include "market/printing/RawSend.hpp"

#include <algorithm>
#include <memory>

#include <spdlog/spdlog.h>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
// winsock2 must precede windows.h or the legacy winsock.h wins and the two
// headers redefine each other's socket types. Same ordering as EscPos.cpp.
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <winspool.h>
#pragma comment(lib, "ws2_32.lib")
#endif

namespace market::printing {
namespace {

std::shared_ptr<spdlog::logger> logger() {
    // Market sets spdlog's default logger in market::logging::init, so the
    // ported code keeps its spdlog format strings and lands in market-core.log.
    return spdlog::default_logger();
}

#ifdef _WIN32
struct WinsockOnce {
    WinsockOnce() {
        WSADATA data{};
        const int rc = WSAStartup(MAKEWORD(2, 2), &data);
        ok = (rc == 0);
        if (!ok) logger()->error("WSAStartup failed: {}", rc);
    }
    ~WinsockOnce() {
        if (ok) WSACleanup();
    }
    bool ok = false;
};

bool ensureWinsock() {
    static WinsockOnce once;
    return once.ok;
}
#endif

}  // namespace

bool isNetworkPrinter(std::string_view printerName) {
    std::string host;
    int port = 0;
    return parseNetworkPrinter(printerName, host, port);
}

bool parseNetworkPrinter(std::string_view printerName, std::string& host, int& port) {
    host.clear();
    port = 9100;
    if (printerName.empty() || printerName == "virtual" || printerName == "offline" ||
        printerName == "auto") {
        return false;
    }
    if (printerName.rfind("usbraw:", 0) == 0 || printerName.rfind("serial:", 0) == 0) return false;

    std::string name(printerName);
    if (name.rfind("tcp:", 0) == 0) name = name.substr(4);
    else if (name.rfind("tcp://", 0) == 0) name = name.substr(6);

    const auto colon = name.rfind(':');
    if (colon != std::string::npos && colon + 1 < name.size()) {
        const std::string portStr = name.substr(colon + 1);
        bool digits = !portStr.empty();
        for (char c : portStr) {
            if (c < '0' || c > '9') {
                digits = false;
                break;
            }
        }
        if (digits) {
            host = name.substr(0, colon);
            port = std::stoi(portStr);
            return !host.empty() && port > 0 && port < 65536;
        }
    }

    // Bare IPv4
    int dots = 0;
    for (char c : name) {
        if (c == '.') dots++;
        else if (c < '0' || c > '9') return false;
    }
    if (dots == 3) {
        host = name;
        port = 9100;
        return true;
    }
    return false;
}

bool sendRawTcp(const std::string& host, int port, const std::vector<std::uint8_t>& payload,
                std::string& errorOut, int timeoutMs) {
#ifdef _WIN32
    if (!ensureWinsock()) {
        errorOut = "Winsock init failed";
        return false;
    }

    SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCKET) {
        errorOut = "socket() failed";
        return false;
    }

    DWORD tv = static_cast<DWORD>(timeoutMs);
    setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, reinterpret_cast<const char*>(&tv), sizeof(tv));
    setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, reinterpret_cast<const char*>(&tv), sizeof(tv));

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(static_cast<u_short>(port));
    if (InetPtonA(AF_INET, host.c_str(), &addr.sin_addr) != 1) {
        // try getaddrinfo
        addrinfo hints{};
        hints.ai_family = AF_INET;
        hints.ai_socktype = SOCK_STREAM;
        addrinfo* result = nullptr;
        if (getaddrinfo(host.c_str(), nullptr, &hints, &result) != 0 || !result) {
            closesocket(sock);
            errorOut = "Invalid printer host: " + host;
            return false;
        }
        addr.sin_addr = reinterpret_cast<sockaddr_in*>(result->ai_addr)->sin_addr;
        freeaddrinfo(result);
    }

    if (connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) == SOCKET_ERROR) {
        errorOut = "Cannot connect to printer " + host + ":" + std::to_string(port);
        closesocket(sock);
        return false;
    }

    std::size_t sent = 0;
    while (sent < payload.size()) {
        const int n = send(sock, reinterpret_cast<const char*>(payload.data() + sent),
                           static_cast<int>(payload.size() - sent), 0);
        if (n <= 0) {
            errorOut = "Send to printer failed";
            closesocket(sock);
            return false;
        }
        sent += static_cast<std::size_t>(n);
    }

    closesocket(sock);
    logger()->info("ESC/POS sent {} bytes to {}:{}", payload.size(), host, port);
    return true;
#else
    (void)timeoutMs;
    errorOut = "Network printing is only implemented on Windows";
    (void)host;
    (void)port;
    (void)payload;
    return false;
#endif
}

bool parseWindowsPrinter(std::string_view printerName, std::string& windowsName) {
    windowsName.clear();
    if (printerName.empty() || printerName == "virtual" || printerName == "offline" ||
        printerName == "auto") {
        return false;
    }
    if (isNetworkPrinter(printerName)) return false;
    // The direct-device schemes are handled by their own senders; without this
    // guard the spooler would be asked to open a device path as a queue name.
    if (printerName.rfind("usbraw:", 0) == 0 || printerName.rfind("serial:", 0) == 0) return false;

    std::string name(printerName);
    if (name.rfind("win:", 0) == 0) {
        name = name.substr(4);
    } else if (name.rfind("usb:", 0) == 0) {
        name = name.substr(4);
    }

    // Trim
    while (!name.empty() && (name.front() == ' ' || name.front() == '\t')) name.erase(name.begin());
    while (!name.empty() && (name.back() == ' ' || name.back() == '\t')) name.pop_back();
    if (name.empty()) return false;

    windowsName = name;
    return true;
}

bool sendRawWindowsPrinter(const std::string& printerName, const std::vector<std::uint8_t>& payload,
                           std::string& errorOut) {
#ifdef _WIN32
    if (printerName.empty()) {
        errorOut = "Printer adı boşdur";
        return false;
    }
    if (payload.empty()) {
        errorOut = "Çap məlumatı boşdur";
        return false;
    }

    const int wideLen =
        MultiByteToWideChar(CP_UTF8, 0, printerName.c_str(), -1, nullptr, 0);
    if (wideLen <= 1) {
        errorOut = "Printer adı keçərsizdir";
        return false;
    }
    std::wstring wide(static_cast<std::size_t>(wideLen - 1), L'\0');
    MultiByteToWideChar(CP_UTF8, 0, printerName.c_str(), -1, wide.data(), wideLen);

    HANDLE printer = nullptr;
    if (!OpenPrinterW(wide.data(), &printer, nullptr) || !printer) {
        errorOut = "Printer açıla bilmədi: " + printerName + " (OpenPrinter)";
        return false;
    }

    DOC_INFO_1W doc{};
    doc.pDocName = const_cast<LPWSTR>(L"Milioner POS");
    doc.pOutputFile = nullptr;
    doc.pDatatype = const_cast<LPWSTR>(L"RAW");

    const DWORD jobId = StartDocPrinterW(printer, 1, reinterpret_cast<LPBYTE>(&doc));
    if (jobId == 0) {
        errorOut = "StartDocPrinter uğursuz oldu";
        ClosePrinter(printer);
        return false;
    }

    if (!StartPagePrinter(printer)) {
        errorOut = "StartPagePrinter uğursuz oldu";
        EndDocPrinter(printer);
        ClosePrinter(printer);
        return false;
    }

    DWORD written = 0;
    const BOOL ok = WritePrinter(printer, const_cast<std::uint8_t*>(payload.data()),
                                 static_cast<DWORD>(payload.size()), &written);
    EndPagePrinter(printer);
    EndDocPrinter(printer);
    ClosePrinter(printer);

    if (!ok || written != payload.size()) {
        errorOut = "WritePrinter uğursuz oldu (" + std::to_string(written) + "/" +
                   std::to_string(payload.size()) + ")";
        return false;
    }

    logger()->info("ESC/POS sent {} bytes to Windows printer '{}'", payload.size(), printerName);
    return true;
#else
    errorOut = "USB/Windows printing is only implemented on Windows";
    (void)printerName;
    (void)payload;
    return false;
#endif
}

bool parseUsbRawPrinter(std::string_view printerName, std::string& devicePath) {
    devicePath.clear();
    if (printerName.rfind("usbraw:", 0) != 0) return false;

    devicePath.assign(printerName.substr(7));
    while (!devicePath.empty() && (devicePath.front() == ' ' || devicePath.front() == '\t')) {
        devicePath.erase(devicePath.begin());
    }
    while (!devicePath.empty() && (devicePath.back() == ' ' || devicePath.back() == '\t')) {
        devicePath.pop_back();
    }
    return !devicePath.empty();
}

bool sendRawUsbDevice(const std::string& devicePath, const std::vector<std::uint8_t>& payload,
                      std::string& errorOut) {
#ifdef _WIN32
    if (devicePath.empty()) {
        errorOut = "USB cihaz yolu boşdur";
        return false;
    }
    if (payload.empty()) {
        errorOut = "Çap məlumatı boşdur";
        return false;
    }

    const int wideLen = MultiByteToWideChar(CP_UTF8, 0, devicePath.c_str(), -1, nullptr, 0);
    if (wideLen <= 1) {
        errorOut = "USB cihaz yolu keçərsizdir";
        return false;
    }
    std::wstring wide(static_cast<std::size_t>(wideLen - 1), L'\0');
    MultiByteToWideChar(CP_UTF8, 0, devicePath.c_str(), -1, wide.data(), wideLen);

    // FILE_SHARE_READ only: two concurrent writers would interleave ESC/POS
    // frames and produce one unreadable receipt instead of two readable ones.
    HANDLE device = CreateFileW(wide.c_str(), GENERIC_WRITE, FILE_SHARE_READ, nullptr,
                                OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (device == INVALID_HANDLE_VALUE) {
        errorOut = "USB printer açıla bilmədi (kod " + std::to_string(GetLastError()) + ")";
        return false;
    }

    std::size_t sent = 0;
    while (sent < payload.size()) {
        // 4 KiB at a time: usbprint.sys rejects oversized single transfers on
        // some low-cost bridges, and a short write is retried rather than lost.
        const DWORD chunk =
            static_cast<DWORD>(std::min<std::size_t>(4096, payload.size() - sent));
        DWORD written = 0;
        if (!WriteFile(device, payload.data() + sent, chunk, &written, nullptr) || written == 0) {
            errorOut = "USB printerə yazıla bilmədi (kod " + std::to_string(GetLastError()) + ")";
            CloseHandle(device);
            return false;
        }
        sent += written;
    }

    FlushFileBuffers(device);
    CloseHandle(device);
    logger()->info("ESC/POS sent {} bytes to USB device '{}'", payload.size(), devicePath);
    return true;
#else
    errorOut = "USB printing is only implemented on Windows";
    (void)devicePath;
    (void)payload;
    return false;
#endif
}

bool parseSerialPrinter(std::string_view printerName, std::string& port, int& baud) {
    port.clear();
    baud = 9600;
    if (printerName.rfind("serial:", 0) != 0) return false;

    std::string rest(printerName.substr(7));
    const auto at = rest.rfind('@');
    if (at != std::string::npos && at + 1 < rest.size()) {
        const std::string baudStr = rest.substr(at + 1);
        bool digits = !baudStr.empty();
        for (char c : baudStr) {
            if (c < '0' || c > '9') {
                digits = false;
                break;
            }
        }
        if (digits) {
            baud = std::stoi(baudStr);
            rest = rest.substr(0, at);
        }
    }

    while (!rest.empty() && (rest.front() == ' ' || rest.front() == '\t')) rest.erase(rest.begin());
    while (!rest.empty() && (rest.back() == ' ' || rest.back() == '\t')) rest.pop_back();

    port = rest;
    return !port.empty() && baud > 0;
}

bool sendRawSerial(const std::string& port, int baud, const std::vector<std::uint8_t>& payload,
                   std::string& errorOut) {
#ifdef _WIN32
    if (port.empty()) {
        errorOut = "Serial port boşdur";
        return false;
    }

    // COM10 and above only resolve through the \\.\ device namespace.
    const std::string path = "\\\\.\\" + port;
    const int wideLen = MultiByteToWideChar(CP_UTF8, 0, path.c_str(), -1, nullptr, 0);
    std::wstring wide(static_cast<std::size_t>(wideLen - 1), L'\0');
    MultiByteToWideChar(CP_UTF8, 0, path.c_str(), -1, wide.data(), wideLen);

    HANDLE device = CreateFileW(wide.c_str(), GENERIC_WRITE, 0, nullptr, OPEN_EXISTING,
                                FILE_ATTRIBUTE_NORMAL, nullptr);
    if (device == INVALID_HANDLE_VALUE) {
        errorOut = port + " açıla bilmədi (kod " + std::to_string(GetLastError()) + ")";
        return false;
    }

    DCB dcb{};
    dcb.DCBlength = sizeof(dcb);
    if (!GetCommState(device, &dcb)) {
        errorOut = "GetCommState uğursuz oldu";
        CloseHandle(device);
        return false;
    }
    dcb.BaudRate = static_cast<DWORD>(baud);
    dcb.ByteSize = 8;
    dcb.Parity = NOPARITY;
    dcb.StopBits = ONESTOPBIT;
    // Hardware flow control: thermal heads stall mid-receipt while the buffer
    // drains, and without RTS/CTS those bytes are silently dropped.
    dcb.fOutxCtsFlow = TRUE;
    dcb.fRtsControl = RTS_CONTROL_HANDSHAKE;
    if (!SetCommState(device, &dcb)) {
        errorOut = "SetCommState uğursuz oldu";
        CloseHandle(device);
        return false;
    }

    COMMTIMEOUTS timeouts{};
    timeouts.WriteTotalTimeoutConstant = 8000;
    timeouts.WriteTotalTimeoutMultiplier = 1;
    SetCommTimeouts(device, &timeouts);

    std::size_t sent = 0;
    while (sent < payload.size()) {
        DWORD written = 0;
        const DWORD chunk =
            static_cast<DWORD>(std::min<std::size_t>(1024, payload.size() - sent));
        if (!WriteFile(device, payload.data() + sent, chunk, &written, nullptr) || written == 0) {
            errorOut = port + " portuna yazıla bilmədi (kod " + std::to_string(GetLastError()) + ")";
            CloseHandle(device);
            return false;
        }
        sent += written;
    }

    FlushFileBuffers(device);
    CloseHandle(device);
    logger()->info("ESC/POS sent {} bytes to {} @ {} baud", payload.size(), port, baud);
    return true;
#else
    errorOut = "Serial printing is only implemented on Windows";
    (void)port;
    (void)baud;
    (void)payload;
    return false;
#endif
}

bool sendOnce(const std::string& target, const std::vector<std::uint8_t>& bytes,
              std::string& errorOut) {
    // Order matters: a target is tried as the most specific thing it could be.
    // A Windows queue name is last because it is the shape with no marker -
    // anything that did not look like the others is treated as a queue.
    std::string host;
    int port = 9100;
    if (parseNetworkPrinter(target, host, port)) return sendRawTcp(host, port, bytes, errorOut);

    std::string devicePath;
    if (parseUsbRawPrinter(target, devicePath)) return sendRawUsbDevice(devicePath, bytes, errorOut);

    std::string serialPort;
    int baud = 9600;
    if (parseSerialPrinter(target, serialPort, baud)) {
        return sendRawSerial(serialPort, baud, bytes, errorOut);
    }

    std::string windowsName;
    if (parseWindowsPrinter(target, windowsName)) {
        return sendRawWindowsPrinter(windowsName, bytes, errorOut);
    }

    errorOut = "Naməlum printer hədəfi: " + target;
    return false;
}

}  // namespace market::printing
