/**
 * AUTO-GENERATED from shared/contracts/protocol.json - DO NOT EDIT.
 * Regenerate with: node scripts/gen-protocol.mjs
 */

export const PROTOCOL_VERSION = 1 as const;

export const LIMITS = {
  maxMessageBytes: 8388608,
  maxInboundQueue: 256,
  maxPendingRequests: 200,
  defaultTimeoutMs: 3000,
  handshakeTimeoutMs: 10000,
  heartbeatIntervalMs: 5000,
  heartbeatTimeoutMs: 2000,
  heartbeatMissLimit: 3,
  coreStallKillMs: 90000,
  printTimeoutMs: 20000,
  paymentTimeoutMs: 120000,
  terminalTimeoutMs: 90000,
  terminalAckTimeoutMs: 15000,
  restartBackoffMs: [500,2000,5000],
  crashWindowMs: 60000,
  crashStrikeLimit: 3,
} as const;

export const ERROR_CODES = [
  'E_INTERNAL',
  'E_INVALID_REQUEST',
  'E_UNKNOWN_METHOD',
  'E_PROTOCOL_VERSION',
  'E_PAYLOAD_TOO_LARGE',
  'E_QUEUE_FULL',
  'E_TIMEOUT',
  'E_CANCELED',
  'E_CORE_DOWN',
  'E_CORE_UNAVAILABLE',
  'E_CORE_MISSING',
  'E_CORE_INCOMPATIBLE',
  'E_CRASH_LOOP',
  'E_DB_BUSY',
  'E_DB_OPEN',
  'E_DB_CORRUPT',
  'E_DB_READONLY',
  'E_DB_UNSUITABLE_LOCATION',
  'E_DISK_FULL',
  'E_CONSTRAINT',
  'E_MIGRATION_FAILED',
  'E_VALIDATION',
  'E_NOT_FOUND',
  'E_UNAUTHORIZED',
  'E_FORBIDDEN',
  'E_INVALID_PIN',
  'E_PIN_LOCKED',
  'E_PIN_CHANGE_REQUIRED',
  'E_MANAGER_APPROVAL_REQUIRED',
  'E_IDEMPOTENCY_KEY_REUSE',
  'E_IN_PROGRESS',
  'E_ORDER_NOT_FOUND',
  'E_ORDER_STATE',
  'E_ORDER_EMPTY',
  'E_SOLD_OUT',
  'E_MODIFIER_REQUIRED',
  'E_MODIFIER_LIMIT',
  'E_TABLE_NOT_FOUND',
  'E_TABLE_OCCUPIED',
  'E_TABLE_STATE',
  'E_PAYMENT_NOT_FOUND',
  'E_PAYMENT_STATE',
  'E_PAYMENT_UNKNOWN_PENDING',
  'E_INSUFFICIENT_PAYMENT',
  'E_OVERPAYMENT',
  'E_PRINTER_UNAVAILABLE',
  'E_PRINT_JOB_NOT_FOUND',
  'E_SHIFT_NOT_OPEN',
  'E_SHIFT_ALREADY_OPEN',
  'E_CONFLICT',
  'E_STALE_VERSION',
  'E_BUSINESS_DAY_CLOSED',
  'E_BUSINESS_DAY_NOT_READY',
  'E_LICENSE_REQUIRED',
  'E_LICENSE_EXPIRED',
  'E_LICENSE_REVOKED',
  'E_FEATURE_DISABLED',
  'E_GIFT_REVIEW_REQUIRED',
  'E_REFUND_LIMIT',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ErrorMeta { retryable: boolean; message: string; fatal: boolean }
export const ERROR_META: Record<ErrorCode, ErrorMeta> = {
  E_INTERNAL: { retryable: false, message: "Internal core error", fatal: false },
  E_INVALID_REQUEST: { retryable: false, message: "Malformed request envelope", fatal: false },
  E_UNKNOWN_METHOD: { retryable: false, message: "Unknown method", fatal: false },
  E_PROTOCOL_VERSION: { retryable: false, message: "Protocol version mismatch", fatal: false },
  E_PAYLOAD_TOO_LARGE: { retryable: false, message: "Payload exceeds maximum message size", fatal: false },
  E_QUEUE_FULL: { retryable: true, message: "Core request queue is full", fatal: false },
  E_TIMEOUT: { retryable: true, message: "Request timed out", fatal: false },
  E_CANCELED: { retryable: false, message: "Request was canceled", fatal: false },
  E_CORE_DOWN: { retryable: true, message: "POS core process is not running", fatal: false },
  E_CORE_UNAVAILABLE: { retryable: true, message: "POS core is starting up", fatal: false },
  E_CORE_MISSING: { retryable: false, message: "POS core executable was not found", fatal: false },
  E_CORE_INCOMPATIBLE: { retryable: false, message: "POS core version is incompatible", fatal: false },
  E_CRASH_LOOP: { retryable: false, message: "POS core is crash looping", fatal: false },
  E_DB_BUSY: { retryable: true, message: "Database is busy", fatal: false },
  E_DB_OPEN: { retryable: false, message: "Database could not be opened", fatal: false },
  E_DB_CORRUPT: { retryable: false, message: "Database file is corrupt", fatal: true },
  E_DB_READONLY: { retryable: false, message: "Database is read only", fatal: false },
  E_DB_UNSUITABLE_LOCATION: { retryable: false, message: "Database location does not support WAL journaling", fatal: true },
  E_DISK_FULL: { retryable: false, message: "Disk is full", fatal: false },
  E_CONSTRAINT: { retryable: false, message: "Database constraint violation", fatal: false },
  E_MIGRATION_FAILED: { retryable: false, message: "Database migration failed", fatal: true },
  E_VALIDATION: { retryable: false, message: "Request payload failed validation", fatal: false },
  E_NOT_FOUND: { retryable: false, message: "Resource was not found", fatal: false },
  E_UNAUTHORIZED: { retryable: false, message: "Authentication required", fatal: false },
  E_FORBIDDEN: { retryable: false, message: "Insufficient permissions", fatal: false },
  E_INVALID_PIN: { retryable: false, message: "Incorrect PIN", fatal: false },
  E_PIN_LOCKED: { retryable: false, message: "Account locked after too many failed attempts", fatal: false },
  E_PIN_CHANGE_REQUIRED: { retryable: false, message: "The default PIN must be changed before signing in", fatal: false },
  E_MANAGER_APPROVAL_REQUIRED: { retryable: false, message: "This action requires manager approval", fatal: false },
  E_IDEMPOTENCY_KEY_REUSE: { retryable: false, message: "Idempotency key reused with a different payload", fatal: false },
  E_IN_PROGRESS: { retryable: true, message: "An identical request is still in progress", fatal: false },
  E_ORDER_NOT_FOUND: { retryable: false, message: "Order was not found", fatal: false },
  E_ORDER_STATE: { retryable: false, message: "Operation is not valid for the current order state", fatal: false },
  E_ORDER_EMPTY: { retryable: false, message: "Order has no items", fatal: false },
  E_SOLD_OUT: { retryable: false, message: "Product is sold out", fatal: false },
  E_MODIFIER_REQUIRED: { retryable: false, message: "A required modifier group has no selection", fatal: false },
  E_MODIFIER_LIMIT: { retryable: false, message: "Modifier selection count is outside the allowed range", fatal: false },
  E_TABLE_NOT_FOUND: { retryable: false, message: "Table was not found", fatal: false },
  E_TABLE_OCCUPIED: { retryable: false, message: "Table already has an open order", fatal: false },
  E_TABLE_STATE: { retryable: false, message: "Operation is not valid for the current table state", fatal: false },
  E_PAYMENT_NOT_FOUND: { retryable: false, message: "Payment was not found", fatal: false },
  E_PAYMENT_STATE: { retryable: false, message: "Illegal payment state transition", fatal: false },
  E_PAYMENT_UNKNOWN_PENDING: { retryable: false, message: "Order has an unresolved payment that must be reconciled first", fatal: false },
  E_INSUFFICIENT_PAYMENT: { retryable: false, message: "Payments do not cover the order total", fatal: false },
  E_OVERPAYMENT: { retryable: false, message: "Payment exceeds the outstanding balance", fatal: false },
  E_PRINTER_UNAVAILABLE: { retryable: true, message: "Printer is unavailable", fatal: false },
  E_PRINT_JOB_NOT_FOUND: { retryable: false, message: "Print job was not found", fatal: false },
  E_SHIFT_NOT_OPEN: { retryable: false, message: "No shift is currently open", fatal: false },
  E_SHIFT_ALREADY_OPEN: { retryable: false, message: "A shift is already open on this terminal", fatal: false },
  E_CONFLICT: { retryable: false, message: "The operation conflicts with the current state", fatal: false },
  E_STALE_VERSION: { retryable: true, message: "Resource was modified by another operator; refresh and retry", fatal: false },
  E_BUSINESS_DAY_CLOSED: { retryable: false, message: "Business day is closed", fatal: false },
  E_BUSINESS_DAY_NOT_READY: { retryable: false, message: "Business day is not ready for Z close", fatal: false },
  E_LICENSE_REQUIRED: { retryable: false, message: "A valid license is required", fatal: false },
  E_LICENSE_EXPIRED: { retryable: false, message: "License has expired", fatal: false },
  E_LICENSE_REVOKED: { retryable: false, message: "License has been revoked", fatal: false },
  E_FEATURE_DISABLED: { retryable: false, message: "This feature is disabled by license flags", fatal: false },
  E_GIFT_REVIEW_REQUIRED: { retryable: false, message: "Gift selection requires manager review", fatal: false },
  E_REFUND_LIMIT: { retryable: false, message: "Refund exceeds remaining refundable amount", fatal: false },
};

export function isErrorCode(v: unknown): v is ErrorCode {
  return typeof v === "string" && Object.prototype.hasOwnProperty.call(ERROR_META, v);
}

export const METHODS = [
  'core.ping',
  'core.info',
  'core.stats',
  'auth.listUsers',
  'auth.login',
  'auth.logout',
  'auth.verifyManagerPin',
  'users.create',
  'users.update',
  'permissions.list',
  'roles.list',
  'roles.save',
  'roles.delete',
  'roles.applyPolicy',
  'users.setPin',
  'users.deactivate',
  'users.list',
  'warehouses.list',
  'warehouses.save',
  'ingredients.list',
  'ingredients.save',
  'ingredients.deactivate',
  'inventory.levels',
  'inventory.lowStock',
  'inventory.valuation',
  'inventory.movements',
  'inventory.adjust',
  'inventory.transfer',
  'inventory.waste',
  'recipes.get',
  'recipes.save',
  'stocktake.create',
  'stocktake.get',
  'stocktake.list',
  'stocktake.count',
  'stocktake.post',
  'suppliers.list',
  'suppliers.save',
  'suppliers.ledger',
  'suppliers.payments',
  'suppliers.pay',
  'purchases.list',
  'purchases.get',
  'purchases.save',
  'purchases.receive',
  'customers.list',
  'customers.get',
  'customers.save',
  'customers.deactivate',
  'customers.ledger',
  'customers.payments',
  'customers.charge',
  'customers.payDebt',
  'loyalty.earn',
  'loyalty.redeem',
  'loyalty.ledger',
  'reservations.list',
  'reservations.save',
  'reservations.setStatus',
  'reservations.seat',
  'couriers.list',
  'couriers.save',
  'delivery.list',
  'delivery.create',
  'delivery.assign',
  'delivery.setStatus',
  'delivery.courierReport',
  'schedule.list',
  'schedule.save',
  'schedule.remove',
  'attendance.clockIn',
  'attendance.clockOut',
  'attendance.list',
  'reports.costing',
  'reports.export',
  'catalog.categories',
  'catalog.products',
  'catalog.product',
  'catalog.modifierGroups',
  'catalog.setAvailability',
  'tables.list',
  'tables.get',
  'tables.setStatus',
  'tables.transfer',
  'tables.merge',
  'tables.split',
  'orders.create',
  'orders.get',
  'orders.list',
  'orders.addItem',
  'orders.updateItemQuantity',
  'orders.setItemNote',
  'orders.setItemSeat',
  'orders.setItemCourse',
  'orders.holdItem',
  'orders.removeItem',
  'orders.voidItem',
  'orders.applyDiscount',
  'orders.setDeposit',
  'orders.setGuestCount',
  'orders.submit',
  'orders.close',
  'orders.void',
  'kds.list',
  'kds.setStatus',
  'kds.bump',
  'payments.list',
  'payments.get',
  'payments.createCash',
  'payments.createCard',
  'payments.cancel',
  'payments.reconcile',
  'payments.refund',
  'payments.unresolved',
  'payments.simulate',
  'receipts.preview',
  'receipts.get',
  'receipts.lookupByCode',
  'print.enqueue',
  'print.jobs',
  'print.retry',
  'print.cancel',
  'print.printers',
  'print.detect',
  'print.setPrinter',
  'print.previewTest',
  'receiptLogo.apply',
  'receiptLogo.clear',
  'shifts.current',
  'shifts.open',
  'shifts.close',
  'settings.getAll',
  'settings.set',
  'settings.applyProvisionedIdentity',
  'audit.list',
  'audit.pending',
  'audit.ack',
  'reports.dashboard',
  'reports.topProducts',
  'reports.salesSummary',
  'reports.period',
  'reports.remotePeriod',
  'reports.x',
  'reports.z',
  'reports.list',
  'reports.getSnapshot',
  'businessDay.current',
  'businessDay.open',
  'businessDay.readiness',
  'businessDay.close',
  'tables.previewTransfer',
  'tables.swap',
  'tables.transferItems',
  'tables.updateLayout',
  'tables.upsertArea',
  'tables.archiveArea',
  'tables.upsertTable',
  'tables.archiveTable',
  'catalog.upsertCategory',
  'catalog.archiveCategory',
  'catalog.upsertProduct',
  'catalog.archiveProduct',
  'catalog.setSoldOut',
  'catalog.setImageHidden',
  'catalog.setAllImagesHidden',
  'catalog.priceHistory',
  'catalog.upsertModifierGroup',
  'catalog.upsertModifier',
  'catalog.archiveModifier',
  'catalog.setProductModifierGroups',
  'catalog.importPreview',
  'catalog.importCommit',
  'catalog.export',
  'gifts.listCampaigns',
  'gifts.upsertCampaign',
  'gifts.evaluateOrder',
  'gifts.apply',
  'gifts.approveReview',
  'cash.list',
  'cash.movement',
  'payments.createMixed',
  'payments.splitBill',
  'payments.listRefunds',
  'license.status',
  'license.activate',
  'license.importOffline',
  'license.exportOfflineRequest',
  'license.heartbeat',
  'license.lookup',
  'tenant.status',
  'tenant.login',
  'tenant.logout',
  'tenant.openPaymentUrl',
  'whatsapp.get',
  'whatsapp.save',
  'whatsapp.connect',
  'whatsapp.status',
  'whatsapp.disconnect',
  'whatsapp.test',
  'backup.create',
  'backup.list',
  'backup.restorePreview',
  'backup.restore',
  'system.resetOperational',
  'sync.status',
  'sync.outbox',
] as const;
export type MethodName = (typeof METHODS)[number];

export interface MethodMeta { auth: boolean; perm: string | null; timeout: number; idempotent: boolean }
export const METHOD_META: Record<MethodName, MethodMeta> = {
  'core.ping': { auth: false, perm: null, timeout: 2000, idempotent: false },
  'core.info': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'core.stats': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'auth.listUsers': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'auth.login': { auth: false, perm: null, timeout: 20000, idempotent: false },
  'auth.logout': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'auth.verifyManagerPin': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'users.create': { auth: true, perm: 'users.manage', timeout: 15000, idempotent: true },
  'users.update': { auth: true, perm: 'users.manage', timeout: 3000, idempotent: true },
  'permissions.list': { auth: true, perm: 'roles.manage', timeout: 3000, idempotent: false },
  'roles.list': { auth: true, perm: 'roles.manage', timeout: 3000, idempotent: false },
  'roles.save': { auth: true, perm: 'roles.manage', timeout: 3000, idempotent: true },
  'roles.delete': { auth: true, perm: 'roles.manage', timeout: 3000, idempotent: true },
  'roles.applyPolicy': { auth: false, perm: null, timeout: 15000, idempotent: false },
  'users.setPin': { auth: true, perm: 'users.manage', timeout: 15000, idempotent: true },
  'users.deactivate': { auth: true, perm: 'users.manage', timeout: 3000, idempotent: true },
  'users.list': { auth: true, perm: 'users.manage', timeout: 3000, idempotent: false },
  'warehouses.list': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'warehouses.save': { auth: true, perm: 'inventory.manage', timeout: 3000, idempotent: true },
  'ingredients.list': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'ingredients.save': { auth: true, perm: 'inventory.manage', timeout: 3000, idempotent: true },
  'ingredients.deactivate': { auth: true, perm: 'inventory.manage', timeout: 3000, idempotent: true },
  'inventory.levels': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'inventory.lowStock': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'inventory.valuation': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'inventory.movements': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'inventory.adjust': { auth: true, perm: 'inventory.adjust', timeout: 3000, idempotent: true },
  'inventory.transfer': { auth: true, perm: 'inventory.transfer', timeout: 3000, idempotent: true },
  'inventory.waste': { auth: true, perm: 'inventory.adjust', timeout: 3000, idempotent: true },
  'recipes.get': { auth: true, perm: 'inventory.view', timeout: 3000, idempotent: false },
  'recipes.save': { auth: true, perm: 'recipes.manage', timeout: 3000, idempotent: true },
  'stocktake.create': { auth: true, perm: 'inventory.count', timeout: 3000, idempotent: true },
  'stocktake.get': { auth: true, perm: 'inventory.count', timeout: 3000, idempotent: false },
  'stocktake.list': { auth: true, perm: 'inventory.count', timeout: 3000, idempotent: false },
  'stocktake.count': { auth: true, perm: 'inventory.count', timeout: 3000, idempotent: false },
  'stocktake.post': { auth: true, perm: 'inventory.count', timeout: 30000, idempotent: true },
  'suppliers.list': { auth: true, perm: 'suppliers.view', timeout: 3000, idempotent: false },
  'suppliers.save': { auth: true, perm: 'suppliers.manage', timeout: 3000, idempotent: true },
  'suppliers.ledger': { auth: true, perm: 'suppliers.view', timeout: 3000, idempotent: false },
  'suppliers.payments': { auth: true, perm: 'suppliers.view', timeout: 3000, idempotent: false },
  'suppliers.pay': { auth: true, perm: 'suppliers.pay', timeout: 3000, idempotent: true },
  'purchases.list': { auth: true, perm: 'suppliers.view', timeout: 3000, idempotent: false },
  'purchases.get': { auth: true, perm: 'suppliers.view', timeout: 3000, idempotent: false },
  'purchases.save': { auth: true, perm: 'suppliers.manage', timeout: 3000, idempotent: true },
  'purchases.receive': { auth: true, perm: 'suppliers.receive', timeout: 30000, idempotent: true },
  'customers.list': { auth: true, perm: 'customers.view', timeout: 3000, idempotent: false },
  'customers.get': { auth: true, perm: 'customers.view', timeout: 3000, idempotent: false },
  'customers.save': { auth: true, perm: 'customers.manage', timeout: 3000, idempotent: true },
  'customers.deactivate': { auth: true, perm: 'customers.manage', timeout: 3000, idempotent: true },
  'customers.ledger': { auth: true, perm: 'customers.view', timeout: 3000, idempotent: false },
  'customers.payments': { auth: true, perm: 'customers.view', timeout: 3000, idempotent: false },
  'customers.charge': { auth: true, perm: 'customers.credit', timeout: 3000, idempotent: true },
  'customers.payDebt': { auth: true, perm: 'customers.credit', timeout: 3000, idempotent: true },
  'loyalty.earn': { auth: true, perm: 'customers.loyalty', timeout: 3000, idempotent: true },
  'loyalty.redeem': { auth: true, perm: 'customers.loyalty', timeout: 3000, idempotent: true },
  'loyalty.ledger': { auth: true, perm: 'customers.view', timeout: 3000, idempotent: false },
  'reservations.list': { auth: true, perm: 'reservations.view', timeout: 3000, idempotent: false },
  'reservations.save': { auth: true, perm: 'reservations.manage', timeout: 3000, idempotent: true },
  'reservations.setStatus': { auth: true, perm: 'reservations.manage', timeout: 3000, idempotent: true },
  'reservations.seat': { auth: true, perm: 'reservations.manage', timeout: 3000, idempotent: true },
  'couriers.list': { auth: true, perm: 'delivery.view', timeout: 3000, idempotent: false },
  'couriers.save': { auth: true, perm: 'delivery.manage', timeout: 3000, idempotent: true },
  'delivery.list': { auth: true, perm: 'delivery.view', timeout: 3000, idempotent: false },
  'delivery.create': { auth: true, perm: 'delivery.manage', timeout: 3000, idempotent: true },
  'delivery.assign': { auth: true, perm: 'delivery.assign', timeout: 3000, idempotent: true },
  'delivery.setStatus': { auth: true, perm: 'delivery.assign', timeout: 3000, idempotent: true },
  'delivery.courierReport': { auth: true, perm: 'delivery.view', timeout: 3000, idempotent: false },
  'schedule.list': { auth: true, perm: 'schedule.view', timeout: 3000, idempotent: false },
  'schedule.save': { auth: true, perm: 'schedule.manage', timeout: 3000, idempotent: true },
  'schedule.remove': { auth: true, perm: 'schedule.manage', timeout: 3000, idempotent: true },
  'attendance.clockIn': { auth: true, perm: 'schedule.clock', timeout: 3000, idempotent: true },
  'attendance.clockOut': { auth: true, perm: 'schedule.clock', timeout: 3000, idempotent: true },
  'attendance.list': { auth: true, perm: 'schedule.view', timeout: 3000, idempotent: false },
  'reports.costing': { auth: true, perm: 'inventory.view', timeout: 10000, idempotent: false },
  'reports.export': { auth: true, perm: 'reports.export', timeout: 30000, idempotent: false },
  'catalog.categories': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'catalog.products': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'catalog.product': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'catalog.modifierGroups': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'catalog.setAvailability': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'tables.list': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'tables.get': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'tables.setStatus': { auth: true, perm: 'tables.status', timeout: 3000, idempotent: false },
  'tables.transfer': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: true },
  'tables.merge': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: true },
  'tables.split': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: true },
  'orders.create': { auth: true, perm: null, timeout: 3000, idempotent: true },
  'orders.get': { auth: true, perm: 'order.view', timeout: 3000, idempotent: false },
  'orders.list': { auth: true, perm: 'order.view', timeout: 3000, idempotent: false },
  'orders.addItem': { auth: true, perm: null, timeout: 3000, idempotent: true },
  'orders.updateItemQuantity': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.setItemNote': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.setItemSeat': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.setItemCourse': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.holdItem': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.removeItem': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.voidItem': { auth: true, perm: 'order.void', timeout: 3000, idempotent: false },
  'orders.applyDiscount': { auth: true, perm: 'order.discount', timeout: 3000, idempotent: false },
  'orders.setDeposit': { auth: true, perm: 'payment.take', timeout: 3000, idempotent: false },
  'orders.setGuestCount': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'orders.submit': { auth: true, perm: null, timeout: 8000, idempotent: true },
  'orders.close': { auth: true, perm: null, timeout: 3000, idempotent: true },
  'orders.void': { auth: true, perm: 'order.void', timeout: 3000, idempotent: true },
  'kds.list': { auth: true, perm: 'kds.view', timeout: 3000, idempotent: false },
  'kds.setStatus': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'kds.bump': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'payments.list': { auth: true, perm: 'payment.view', timeout: 3000, idempotent: false },
  'payments.get': { auth: true, perm: 'payment.view', timeout: 3000, idempotent: false },
  'payments.createCash': { auth: true, perm: null, timeout: 30000, idempotent: true },
  'payments.createCard': { auth: true, perm: null, timeout: 120000, idempotent: true },
  'payments.cancel': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'payments.reconcile': { auth: true, perm: 'payment.reconcile', timeout: 30000, idempotent: false },
  'payments.refund': { auth: true, perm: 'payment.refund', timeout: 120000, idempotent: true },
  'payments.unresolved': { auth: true, perm: 'payment.reconcile', timeout: 3000, idempotent: false },
  'payments.simulate': { auth: true, perm: 'settings.manage', timeout: 3000, idempotent: false },
  'receipts.preview': { auth: true, perm: null, timeout: 8000, idempotent: false },
  'receipts.get': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'receipts.lookupByCode': { auth: true, perm: 'payment.refund', timeout: 8000, idempotent: false },
  'print.enqueue': { auth: true, perm: 'receipt.print', timeout: 20000, idempotent: true },
  'print.jobs': { auth: true, perm: null, timeout: 10000, idempotent: false },
  'print.retry': { auth: true, perm: null, timeout: 10000, idempotent: false },
  'print.cancel': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'print.printers': { auth: true, perm: 'printer.manage', timeout: 20000, idempotent: false },
  'print.detect': { auth: true, perm: 'settings.manage', timeout: 60000, idempotent: false },
  'print.setPrinter': { auth: true, perm: 'settings.manage', timeout: 3000, idempotent: false },
  'print.previewTest': { auth: true, perm: null, timeout: 8000, idempotent: false },
  'receiptLogo.apply': { auth: true, perm: 'settings.manage', timeout: 60000, idempotent: false },
  'receiptLogo.clear': { auth: true, perm: 'settings.manage', timeout: 60000, idempotent: false },
  'shifts.current': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'shifts.open': { auth: true, perm: 'shift.manage', timeout: 3000, idempotent: true },
  'shifts.close': { auth: true, perm: 'shift.manage', timeout: 3000, idempotent: true },
  'settings.getAll': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'settings.set': { auth: true, perm: 'settings.manage', timeout: 3000, idempotent: false },
  'settings.applyProvisionedIdentity': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'audit.list': { auth: true, perm: 'audit.view', timeout: 3000, idempotent: false },
  'audit.pending': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'audit.ack': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'reports.dashboard': { auth: true, perm: 'reports.view', timeout: 3000, idempotent: false },
  'reports.topProducts': { auth: true, perm: 'reports.view', timeout: 3000, idempotent: false },
  'reports.salesSummary': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'reports.period': { auth: true, perm: 'reports.view', timeout: 10000, idempotent: false },
  'reports.remotePeriod': { auth: false, perm: null, timeout: 15000, idempotent: false },
  'reports.x': { auth: true, perm: 'reports.x', timeout: 30000, idempotent: true },
  'reports.z': { auth: true, perm: 'reports.z', timeout: 30000, idempotent: true },
  'reports.list': { auth: true, perm: 'reports.view', timeout: 3000, idempotent: false },
  'reports.getSnapshot': { auth: true, perm: 'reports.view', timeout: 3000, idempotent: false },
  'businessDay.current': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'businessDay.open': { auth: true, perm: 'businessDay.manage', timeout: 3000, idempotent: true },
  'businessDay.readiness': { auth: true, perm: 'reports.z', timeout: 3000, idempotent: false },
  'businessDay.close': { auth: true, perm: 'businessDay.manage', timeout: 30000, idempotent: true },
  'tables.previewTransfer': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: false },
  'tables.swap': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: true },
  'tables.transferItems': { auth: true, perm: 'order.transfer', timeout: 3000, idempotent: true },
  'tables.updateLayout': { auth: true, perm: 'tables.layout', timeout: 3000, idempotent: true },
  'tables.upsertArea': { auth: true, perm: 'tables.layout', timeout: 3000, idempotent: true },
  'tables.archiveArea': { auth: true, perm: 'tables.layout', timeout: 3000, idempotent: false },
  'tables.upsertTable': { auth: true, perm: 'tables.layout', timeout: 3000, idempotent: true },
  'tables.archiveTable': { auth: true, perm: 'tables.layout', timeout: 3000, idempotent: false },
  'catalog.upsertCategory': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: true },
  'catalog.archiveCategory': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.upsertProduct': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: true },
  'catalog.archiveProduct': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.setSoldOut': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.setImageHidden': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.setAllImagesHidden': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.priceHistory': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.upsertModifierGroup': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: true },
  'catalog.upsertModifier': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: true },
  'catalog.archiveModifier': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: false },
  'catalog.setProductModifierGroups': { auth: true, perm: 'catalog.manage', timeout: 3000, idempotent: true },
  'catalog.importPreview': { auth: true, perm: 'catalog.import', timeout: 3000, idempotent: false },
  'catalog.importCommit': { auth: true, perm: 'catalog.import', timeout: 3000, idempotent: true },
  'catalog.export': { auth: true, perm: 'catalog.import', timeout: 3000, idempotent: false },
  'gifts.listCampaigns': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'gifts.upsertCampaign': { auth: true, perm: 'gifts.manage', timeout: 3000, idempotent: true },
  'gifts.evaluateOrder': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'gifts.apply': { auth: true, perm: null, timeout: 3000, idempotent: true },
  'gifts.approveReview': { auth: true, perm: 'gifts.override', timeout: 3000, idempotent: false },
  'cash.list': { auth: true, perm: 'cash.manage', timeout: 3000, idempotent: false },
  'cash.movement': { auth: true, perm: 'cash.manage', timeout: 3000, idempotent: true },
  'payments.createMixed': { auth: true, perm: null, timeout: 120000, idempotent: true },
  'payments.splitBill': { auth: true, perm: 'payment.split', timeout: 3000, idempotent: true },
  'payments.listRefunds': { auth: true, perm: 'payment.refund', timeout: 3000, idempotent: false },
  'license.status': { auth: false, perm: null, timeout: 15000, idempotent: false },
  'license.activate': { auth: false, perm: null, timeout: 3000, idempotent: true },
  'license.importOffline': { auth: false, perm: null, timeout: 3000, idempotent: true },
  'license.exportOfflineRequest': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'license.heartbeat': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'license.lookup': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'tenant.status': { auth: false, perm: null, timeout: 15000, idempotent: false },
  'tenant.login': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'tenant.logout': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'tenant.openPaymentUrl': { auth: false, perm: null, timeout: 3000, idempotent: false },
  'whatsapp.get': { auth: true, perm: 'settings.manage', timeout: 20000, idempotent: false },
  'whatsapp.save': { auth: true, perm: 'settings.manage', timeout: 20000, idempotent: false },
  'whatsapp.connect': { auth: true, perm: 'settings.manage', timeout: 45000, idempotent: false },
  'whatsapp.status': { auth: true, perm: 'settings.manage', timeout: 20000, idempotent: false },
  'whatsapp.disconnect': { auth: true, perm: 'settings.manage', timeout: 20000, idempotent: false },
  'whatsapp.test': { auth: true, perm: 'settings.manage', timeout: 30000, idempotent: false },
  'backup.create': { auth: true, perm: 'backup.manage', timeout: 120000, idempotent: false },
  'backup.list': { auth: true, perm: 'backup.manage', timeout: 3000, idempotent: false },
  'backup.restorePreview': { auth: true, perm: 'backup.manage', timeout: 3000, idempotent: false },
  'backup.restore': { auth: true, perm: 'backup.manage', timeout: 180000, idempotent: true },
  'system.resetOperational': { auth: true, perm: 'system.reset', timeout: 120000, idempotent: true },
  'sync.status': { auth: true, perm: null, timeout: 3000, idempotent: false },
  'sync.outbox': { auth: true, perm: null, timeout: 3000, idempotent: false },
};

export const EVENTS = [
  'core.ready',
  'core.stage',
  'core.alert',
  'core.fatal',
  'kds.updated',
  'tables.updated',
  'orders.updated',
  'print.updated',
  'payment.needsReconciliation',
  'reports.created',
] as const;
export type EventName = (typeof EVENTS)[number];

export const ROLES = ['waiter', 'cashier', 'kitchen', 'supervisor', 'manager', 'administrator'] as const;
export type Role = (typeof ROLES)[number];

export const TABLE_STATUSS = ['available', 'occupied', 'reserved', 'waiting', 'ordering', 'preparing', 'ready', 'payment_requested', 'cleaning'] as const;
export type TableStatus = (typeof TABLE_STATUSS)[number];

export const ORDER_STATUSS = ['draft', 'open', 'sent', 'partially_paid', 'paid', 'closed', 'voided'] as const;
export type OrderStatus = (typeof ORDER_STATUSS)[number];

export const ORDER_ITEM_STATUSS = ['draft', 'sent', 'preparing', 'ready', 'served', 'voided', 'held'] as const;
export type OrderItemStatus = (typeof ORDER_ITEM_STATUSS)[number];

export const KITCHEN_STATUSS = ['new', 'accepted', 'preparing', 'ready', 'completed'] as const;
export type KitchenStatus = (typeof KITCHEN_STATUSS)[number];

export const PAYMENT_STATUSS = ['created', 'waiting_for_terminal', 'processing', 'approved', 'declined', 'canceled', 'unknown', 'refunded'] as const;
export type PaymentStatus = (typeof PAYMENT_STATUSS)[number];

export const PAYMENT_METHODS = ['cash', 'card', 'mixed', 'complimentary'] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export const PRINT_JOB_STATUSS = ['queued', 'processing', 'sent', 'failed', 'retrying', 'completed'] as const;
export type PrintJobStatus = (typeof PRINT_JOB_STATUSS)[number];

export const PRINT_JOB_KINDS = ['kitchen_ticket', 'customer_bill', 'customer_receipt', 'shift_report', 'test_page', 'x_report', 'z_report', 'refund_receipt', 'warehouse_slip', 'period_report'] as const;
export type PrintJobKind = (typeof PRINT_JOB_KINDS)[number];

export const CORE_STATES = ['idle', 'spawning', 'handshaking', 'ready', 'restarting', 'crash_loop', 'core_missing', 'incompatible', 'stopping', 'stopped'] as const;
export type CoreState = (typeof CORE_STATES)[number];

export const DISCOUNT_TYPES = ['percent', 'amount', 'complimentary'] as const;
export type DiscountType = (typeof DISCOUNT_TYPES)[number];

export const COURSES = ['starter', 'main', 'dessert', 'drinks'] as const;
export type Course = (typeof COURSES)[number];

export const PERMISSIONS = {
  'order.create': ['waiter', 'cashier', 'supervisor', 'manager', 'administrator'],
  'order.void': ['supervisor', 'manager', 'administrator'],
  'order.discount': ['supervisor', 'manager', 'administrator'],
  'order.transfer': ['waiter', 'supervisor', 'manager', 'administrator'],
  'order.closeOther': ['manager', 'administrator'],
  'order.priceOverride': ['manager', 'administrator'],
  'payment.take': ['cashier', 'waiter', 'supervisor', 'manager', 'administrator'],
  'payment.refund': ['manager', 'administrator'],
  'payment.reconcile': ['supervisor', 'manager', 'administrator'],
  'shift.manage': ['cashier', 'supervisor', 'manager', 'administrator'],
  'kds.operate': ['kitchen', 'supervisor', 'manager', 'administrator'],
  'catalog.manage': ['manager', 'administrator'],
  'settings.manage': ['manager', 'administrator'],
  'audit.view': ['manager', 'administrator'],
  'reports.view': ['supervisor', 'manager', 'administrator'],
  'reports.x': ['cashier', 'supervisor', 'manager', 'administrator'],
  'reports.z': ['manager', 'administrator'],
  'businessDay.manage': ['manager', 'administrator'],
  'cash.manage': ['cashier', 'supervisor', 'manager', 'administrator'],
  'gifts.manage': ['manager', 'administrator'],
  'gifts.override': ['supervisor', 'manager', 'administrator'],
  'catalog.import': ['manager', 'administrator'],
  'backup.manage': ['manager', 'administrator'],
  'system.reset': ['administrator'],
  'license.manage': ['administrator'],
  'tables.layout': ['manager', 'administrator'],
  'payment.split': ['cashier', 'supervisor', 'manager', 'administrator'],
  'discount.manage': ['manager', 'administrator'],
  'users.manage': ['manager', 'administrator'],
} as const;
export type PermissionKey = keyof typeof PERMISSIONS;

export function roleHasPermission(role: Role, perm: PermissionKey): boolean {
  return (PERMISSIONS[perm] as readonly string[]).includes(role);
}
