/*
 * Ported from the restaurant core (native/core/src/printing/DeviceDiscovery.cpp).
 *
 * Generated by scripts/port-printing-from-restaurant.mjs. Fix the restaurant
 * source and re-run rather than editing this copy, or the two drift and the
 * market till quietly loses a fix the restaurant got.
 */
#include "market/printing/DeviceDiscovery.hpp"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <unordered_set>

#include <spdlog/spdlog.h>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
// winsock2 must precede windows.h or the legacy winsock.h wins and the two
// headers redefine each other's socket types. Same ordering as EscPos.cpp.
#include <winsock2.h>
#include <ws2tcpip.h>
#include <iphlpapi.h>
#include <windows.h>
#include <winioctl.h>
#include <setupapi.h>
#include <devguid.h>
#include <winspool.h>
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "iphlpapi.lib")

// usbprint.h declares GUID_DEVINTERFACE_USBPRINT but no toolchain import
// library defines it, so carry our own copy of the well-known value. Likewise
// the SDK ships no constant for the 1284 identity query.
static const GUID kUsbPrintInterface = {
    0x28d78fad, 0x5a12, 0x11d1, {0xae, 0x5b, 0x00, 0x00, 0xf8, 0x03, 0xa8, 0xc2}};

#ifndef IOCTL_USBPRINT_GET_1284_ID
#define IOCTL_USBPRINT_GET_1284_ID \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 14, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif
#endif

namespace market::printing {
namespace {

std::shared_ptr<spdlog::logger> logger() {
    // Market sets spdlog's default logger in market::logging::init, so the
    // ported code keeps its spdlog format strings and lands in market-core.log.
    return spdlog::default_logger();
}

std::string toLower(std::string value) {
    for (char& c : value) {
        if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
    }
    return value;
}

bool contains(std::string_view haystack, std::string_view needle) {
    return haystack.find(needle) != std::string_view::npos;
}

/**
 * Model / driver fragments that mean "thermal receipt printer".
 *
 * Deliberately generous: a false positive only costs one probe page, while a
 * false negative leaves the till unable to print at all.
 */
constexpr std::array<std::string_view, 26> kThermalHints{
    "pos",     "thermal", "receipt", "termal", "58",     "80",      "xp-",
    "xprinter", "tm-",    "epson tm", "star",  "bixolon", "srp-",   "rongta",
    "rp-",     "gprinter", "gp-",    "zj-",    "hprt",   "sam4s",   "citizen",
    "custom",  "generic / text only", "text only", "kassa", "escpos"};

/** Fragments that mean "office printer" - never the till's receipt printer. */
constexpr std::array<std::string_view, 10> kOfficeHints{
    "laserjet", "deskjet", "officejet", "inkjet", "laser",
    "mfp",      "scan",    "photosmart", "ecotank", "a4"};

/**
 * Base score per link kind.
 *
 * `Network` used to sit at 30, below even a bare COM port, so a till whose
 * printer lives on the switch could never win auto-selection. At 45 a raw-print
 * port is worth at least as much as a COM port, and a device that answers
 * `DLE EOT 1` adds `kEscPosConfirmedBonus` on top for 90.
 *
 * That deliberately stays under `UsbRaw`: a USB printer-class device is both
 * certainly a printer and certainly *this* till's printer, whereas a confirmed
 * ESC/POS box on the LAN might belong to the kitchen or the next till over.
 *
 * `Other` drops to 0 so an unrecognised spooler queue is no longer eligible on
 * its own - `deliveryTargets()` only accepts score > 0.
 */
int baseScoreFor(PrinterLink link) {
    switch (link) {
        case PrinterLink::UsbRaw:
            return 100;
        case PrinterLink::UsbQueue:
            return 70;
        case PrinterLink::Network:
            return 45;
        case PrinterLink::Serial:
            return 45;
        case PrinterLink::Lpt:
            return 40;
        case PrinterLink::Other:
            return 0;
        case PrinterLink::Virtual:
            return -50;
    }
    return 0;
}

constexpr int kEscPosConfirmedBonus = 45;
constexpr int kOfflinePenalty = 40;

#ifdef _WIN32
std::string wideToUtf8(const wchar_t* wide) {
    if (!wide) return {};
    const int size = WideCharToMultiByte(CP_UTF8, 0, wide, -1, nullptr, 0, nullptr, nullptr);
    if (size <= 1) return {};
    std::string out(static_cast<std::size_t>(size - 1), '\0');
    WideCharToMultiByte(CP_UTF8, 0, wide, -1, out.data(), size, nullptr, nullptr);
    return out;
}

/** SPDRP_FRIENDLYNAME, falling back to SPDRP_DEVICEDESC. */
std::string deviceName(HDEVINFO set, SP_DEVINFO_DATA& info) {
    for (const DWORD property : {SPDRP_FRIENDLYNAME, SPDRP_DEVICEDESC}) {
        DWORD needed = 0;
        SetupDiGetDeviceRegistryPropertyW(set, &info, property, nullptr, nullptr, 0, &needed);
        if (needed == 0) continue;

        std::vector<BYTE> buffer(needed + sizeof(wchar_t), 0);
        if (SetupDiGetDeviceRegistryPropertyW(set, &info, property, nullptr, buffer.data(), needed,
                                              nullptr)) {
            auto name = wideToUtf8(reinterpret_cast<const wchar_t*>(buffer.data()));
            if (!name.empty()) return name;
        }
    }
    return {};
}

/**
 * Asks the device for its IEEE-1284 identity.
 *
 * Opened read-only and with full sharing so this never steals the handle from
 * an in-flight print job. A device that refuses simply stays unidentified.
 */
std::string queryDeviceId(const std::wstring& devicePath) {
    HANDLE handle = CreateFileW(devicePath.c_str(), GENERIC_READ,
                                FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr, OPEN_EXISTING, 0,
                                nullptr);
    if (handle == INVALID_HANDLE_VALUE) return {};

    std::array<char, 1024> buffer{};
    DWORD returned = 0;
    const BOOL ok = DeviceIoControl(handle, IOCTL_USBPRINT_GET_1284_ID, nullptr, 0, buffer.data(),
                                    static_cast<DWORD>(buffer.size()), &returned, nullptr);
    CloseHandle(handle);
    if (!ok || returned < 2) return {};

    // The reply is prefixed with a big-endian length covering the prefix itself.
    const auto length = static_cast<std::size_t>(
        (static_cast<unsigned char>(buffer[0]) << 8) | static_cast<unsigned char>(buffer[1]));
    const std::size_t available = std::min<std::size_t>(returned, buffer.size());
    if (length <= 2 || length > available) {
        return std::string(buffer.data() + 2, available - 2);
    }
    return std::string(buffer.data() + 2, length - 2);
}
#endif  // _WIN32

}  // namespace

std::string_view linkToString(PrinterLink link) {
    switch (link) {
        case PrinterLink::UsbRaw:
            return "usb";
        case PrinterLink::UsbQueue:
            return "usb";
        case PrinterLink::Serial:
            return "serial";
        case PrinterLink::Lpt:
            return "lpt";
        case PrinterLink::Network:
            return "network";
        case PrinterLink::Other:
            return "other";
        case PrinterLink::Virtual:
            return "virtual";
    }
    return "other";
}

DeviceId parseDeviceId(std::string_view ieee1284) {
    DeviceId out;
    std::size_t cursor = 0;

    while (cursor < ieee1284.size()) {
        const auto end = ieee1284.find(';', cursor);
        const auto field = ieee1284.substr(cursor, end == std::string_view::npos
                                                       ? std::string_view::npos
                                                       : end - cursor);
        cursor = end == std::string_view::npos ? ieee1284.size() : end + 1;

        const auto colon = field.find(':');
        if (colon == std::string_view::npos) continue;

        const auto key = toLower(std::string(field.substr(0, colon)));
        std::string value(field.substr(colon + 1));
        while (!value.empty() && (value.front() == ' ' || value.front() == '\t')) {
            value.erase(value.begin());
        }
        while (!value.empty() && (value.back() == ' ' || value.back() == '\t' ||
                                  value.back() == '\r' || value.back() == '\n')) {
            value.pop_back();
        }

        if (key == "mfg" || key == "manufacturer") out.manufacturer = value;
        else if (key == "mdl" || key == "model") out.model = value;
        else if (key == "cmd" || key == "commandset") out.commandSet = value;
    }
    return out;
}

bool parseUsbIds(std::string_view devicePath, std::string& vendorId, std::string& productId) {
    vendorId.clear();
    productId.clear();

    const std::string lowered = toLower(std::string(devicePath));
    const auto take = [&](std::string_view prefix, std::string& out) {
        const auto at = lowered.find(prefix);
        if (at == std::string::npos) return;
        const auto start = at + prefix.size();
        for (std::size_t i = start; i < lowered.size() && i < start + 4; ++i) {
            const char c = lowered[i];
            const bool hex = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
            if (!hex) break;
            out.push_back(c);
        }
    };

    take("vid_", vendorId);
    take("pid_", productId);
    return !vendorId.empty() && !productId.empty();
}

int scoreCandidate(const PrinterCandidate& candidate) {
    int score = baseScoreFor(candidate.link);

    // A confirmed responder is paid `kEscPosConfirmedBonus` for speaking
    // ESC/POS, so the keyword scan must not charge for the same fact again. The
    // sweep synthesises both `displayName` and `commandSet` from the very reply
    // that earned the bonus, so only device-reported text is scanned here -
    // otherwise a LAN box outranks the USB printer wired to the till.
    const std::string haystack =
        candidate.escposConfirmed
            ? toLower(candidate.manufacturer + " " + candidate.model + " " + candidate.driver)
            : toLower(candidate.displayName + " " + candidate.manufacturer + " " +
                      candidate.model + " " + candidate.driver + " " + candidate.commandSet);

    for (const auto hint : kThermalHints) {
        if (contains(haystack, hint)) {
            score += 12;
            break;
        }
    }
    // ESC/POS in the command set is the strongest signal a device can *claim*;
    // a device that answered the status query has already proven it.
    if (!candidate.escposConfirmed &&
        (contains(haystack, "escpos") || contains(haystack, "esc/pos"))) {
        score += 25;
    }

    for (const auto hint : kOfficeHints) {
        if (contains(haystack, hint)) {
            score -= 80;
            break;
        }
    }

    // A device that answered the real-time status query is a printer, whatever
    // its name says. An offline one stays listed so the settings screen can
    // explain itself, but must not win auto-selection.
    if (candidate.escposConfirmed) {
        score += kEscPosConfirmedBonus;
        if (!decodeEscPosStatus(candidate.statusByte).online) score -= kOfflinePenalty;
    }

    if (candidate.isCurrent) score += 5;
    return score;
}

bool isEscPosStatusByte(std::uint8_t raw) {
    // Bits 0,1,4,7 are fixed at 0,1,1,0 in every DLE EOT 1 reply.
    return (raw & 0x93) == 0x12;
}

EscPosStatus decodeEscPosStatus(std::uint8_t raw) {
    EscPosStatus status;
    status.raw = raw;
    status.valid = isEscPosStatusByte(raw);
    if (!status.valid) return status;

    status.answered = true;
    status.drawerHigh = (raw & 0x04) != 0;
    status.online = (raw & 0x08) == 0;
    status.waitingRecovery = (raw & 0x20) != 0;
    status.feedButton = (raw & 0x40) != 0;
    return status;
}

bool isSoftwarePrinter(std::string_view name, std::string_view port, std::string_view driver) {
    const auto n = toLower(std::string(name));
    const auto p = toLower(std::string(port));
    const auto d = toLower(std::string(driver));

    for (const auto hint : {"onenote", "xps", "pdf", "fax", "microsoft print to"}) {
        if (contains(n, hint)) return true;
        // The queue can be branded anything at all - "PanCafe Printer" on the
        // Microsoft Print To PDF driver is a real example that reached a till
        // and swallowed every receipt - so the driver has to be checked too.
        if (!d.empty() && contains(d, hint)) return true;
    }

    if (p == "portprompt:" || p == "shrfax:" || p == "nul:" || p == "file:") return true;
    if (contains(p, "onenote")) return true;

    // A port that is a filesystem path prints to a file, never to paper.
    if (contains(p, "\\") || contains(p, "/")) {
        for (const auto suffix : {".pdf", ".xps", ".oxps", ".prn", ".ps", ".tif"}) {
            if (p.size() >= std::string_view(suffix).size() &&
                p.compare(p.size() - std::string_view(suffix).size(),
                          std::string_view(suffix).size(), suffix) == 0) {
                return true;
            }
        }
    }
    return false;
}

// ------------------------------------------------------------ network scan --

std::uint32_t ipv4ToUint(std::string_view dotted) {
    std::uint32_t octets[4] = {0, 0, 0, 0};
    std::size_t index = 0;
    std::size_t digits = 0;
    std::uint32_t value = 0;

    for (std::size_t i = 0; i <= dotted.size(); ++i) {
        const bool end = i == dotted.size();
        const char c = end ? '.' : dotted[i];

        if (c == '.') {
            if (digits == 0 || index > 3) return 0;
            if (value > 255) return 0;
            octets[index++] = value;
            value = 0;
            digits = 0;
            continue;
        }
        if (c < '0' || c > '9') return 0;
        if (++digits > 3) return 0;
        value = value * 10 + static_cast<std::uint32_t>(c - '0');
    }

    if (index != 4) return 0;
    return (octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3];
}

std::string uintToIpv4(std::uint32_t value) {
    char buffer[16];
    std::snprintf(buffer, sizeof(buffer), "%u.%u.%u.%u", (value >> 24) & 0xFF,
                  (value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF);
    return buffer;
}

std::vector<std::string> subnetHosts(std::uint32_t address, int prefixLength,
                                     std::size_t maxHosts) {
    std::vector<std::string> hosts;
    if (prefixLength < 1 || prefixLength > 31) return hosts;

    const std::uint64_t size = std::uint64_t{1} << (32 - prefixLength);
    if (size - 2 > maxHosts) return hosts;

    const std::uint32_t mask = static_cast<std::uint32_t>(~(size - 1));
    const std::uint32_t network = address & mask;
    const std::uint32_t broadcast = network + static_cast<std::uint32_t>(size) - 1;

    hosts.reserve(static_cast<std::size_t>(size));
    for (std::uint32_t a = network + 1; a < broadcast; ++a) hosts.push_back(uintToIpv4(a));
    return hosts;
}

std::vector<std::string> buildScanHostList(const NetworkScanOptions& options) {
    std::vector<std::string> ordered;
    std::unordered_set<std::string> seen;

    const auto add = [&](const std::string& host) {
        if (host.empty() || ipv4ToUint(host) == 0) return;
        if (seen.insert(host).second) ordered.push_back(host);
    };

    // a. what we already believe, so a re-verify costs one connect.
    for (const auto& target : options.knownTargets) {
        std::string host = target;
        if (host.rfind("tcp://", 0) == 0) host = host.substr(6);
        else if (host.rfind("tcp:", 0) == 0) host = host.substr(4);
        const auto colon = host.rfind(':');
        if (colon != std::string::npos) host = host.substr(0, colon);
        add(host);
    }

    // b. hosts that have actually exchanged traffic recently. The till printer
    //    is nearly always here, which is why the sweep tail rarely runs.
    for (const auto& host : arpCacheHosts()) add(host);

    // c. anything Windows already knows as a printer port.
    for (const auto& host : printerPortHosts()) add(host);

    // d. the rest of the local subnets.
    if (options.sweepSubnet) {
        for (const auto& [address, prefix] : localScanSubnets()) {
            for (const auto& host : subnetHosts(address, prefix)) add(host);
        }
    }
    return ordered;
}

#ifdef _WIN32

std::vector<std::pair<std::uint32_t, int>> localScanSubnets() {
    std::vector<std::pair<std::uint32_t, int>> subnets;

    ULONG size = 15000;
    std::vector<BYTE> buffer(size);
    auto* addresses = reinterpret_cast<IP_ADAPTER_ADDRESSES*>(buffer.data());
    ULONG result = GetAdaptersAddresses(AF_INET, GAA_FLAG_SKIP_ANYCAST | GAA_FLAG_SKIP_MULTICAST |
                                                     GAA_FLAG_SKIP_DNS_SERVER,
                                        nullptr, addresses, &size);
    if (result == ERROR_BUFFER_OVERFLOW) {
        buffer.assign(size, 0);
        addresses = reinterpret_cast<IP_ADAPTER_ADDRESSES*>(buffer.data());
        result = GetAdaptersAddresses(AF_INET, GAA_FLAG_SKIP_ANYCAST | GAA_FLAG_SKIP_MULTICAST |
                                                   GAA_FLAG_SKIP_DNS_SERVER,
                                      nullptr, addresses, &size);
    }
    if (result != NO_ERROR) {
        logger()->warn("GetAdaptersAddresses failed: {}", result);
        return subnets;
    }

    for (auto* adapter = addresses; adapter != nullptr; adapter = adapter->Next) {
        if (adapter->OperStatus != IfOperStatusUp) continue;
        if (adapter->IfType == IF_TYPE_SOFTWARE_LOOPBACK) continue;

        // A hypervisor's host-only network has no till printer on it and a /24
        // sweep of each one is pure latency.
        const std::string description = wideToUtf8(adapter->Description);
        const std::string lowered = toLower(description);
        if (contains(lowered, "hyper-v") || contains(lowered, "vmware") ||
            contains(lowered, "virtualbox") || contains(lowered, "loopback") ||
            contains(lowered, "wsl") || contains(lowered, "tap-")) {
            continue;
        }

        for (auto* unicast = adapter->FirstUnicastAddress; unicast != nullptr;
             unicast = unicast->Next) {
            if (unicast->Address.lpSockaddr->sa_family != AF_INET) continue;
            const auto* in = reinterpret_cast<sockaddr_in*>(unicast->Address.lpSockaddr);
            const std::uint32_t address = ntohl(in->sin_addr.s_addr);
            if (address == 0) continue;
            if ((address >> 24) == 127) continue;               // loopback
            if ((address & 0xFFFF0000u) == 0xA9FE0000u) continue;  // 169.254/16 APIPA

            const int prefix = unicast->OnLinkPrefixLength;
            if (prefix < 22 || prefix > 31) continue;  // never sweep wider than /22
            subnets.emplace_back(address, prefix);
        }
    }
    return subnets;
}

std::vector<std::string> arpCacheHosts() {
    std::vector<std::string> hosts;

    MIB_IPNET_TABLE2* table = nullptr;
    if (GetIpNetTable2(AF_INET, &table) != NO_ERROR || table == nullptr) return hosts;

    for (ULONG i = 0; i < table->NumEntries; ++i) {
        const auto& row = table->Table[i];
        if (row.State == NlnsUnreachable || row.State == NlnsIncomplete) continue;

        const std::uint32_t address = ntohl(row.Address.Ipv4.sin_addr.s_addr);
        if (address == 0) continue;
        if ((address >> 24) == 127) continue;
        if ((address >> 28) == 0xE) continue;   // 224/4 multicast
        if ((address & 0xFF) == 0xFF) continue; // .255 broadcast
        hosts.push_back(uintToIpv4(address));
    }

    FreeMibTable(table);
    return hosts;
}

std::string macForAddress(std::string_view ipAddress) {
    const std::uint32_t wanted = ipv4ToUint(ipAddress);
    if (wanted == 0) return {};

    MIB_IPNET_TABLE2* table = nullptr;
    if (GetIpNetTable2(AF_INET, &table) != NO_ERROR || table == nullptr) return {};

    std::string mac;
    for (ULONG i = 0; i < table->NumEntries; ++i) {
        const auto& row = table->Table[i];
        if (ntohl(row.Address.Ipv4.sin_addr.s_addr) != wanted) continue;
        if (row.PhysicalAddressLength == 0) break;

        char buffer[3];
        for (ULONG b = 0; b < row.PhysicalAddressLength && b < 8; ++b) {
            std::snprintf(buffer, sizeof(buffer), "%02x", row.PhysicalAddress[b]);
            if (!mac.empty()) mac.push_back(':');
            mac.append(buffer);
        }
        break;
    }

    FreeMibTable(table);
    return mac;
}

std::vector<std::string> printerPortHosts() {
    std::vector<std::string> hosts;

    DWORD needed = 0;
    DWORD returned = 0;
    EnumPortsW(nullptr, 2, nullptr, 0, &needed, &returned);
    if (needed == 0) return hosts;

    std::vector<BYTE> buffer(needed);
    if (!EnumPortsW(nullptr, 2, buffer.data(), needed, &needed, &returned)) return hosts;

    auto* ports = reinterpret_cast<PORT_INFO_2W*>(buffer.data());
    for (DWORD i = 0; i < returned; ++i) {
        if (!ports[i].pPortName) continue;
        // A Standard TCP/IP port is conventionally named IP_<address>.
        std::string name = wideToUtf8(ports[i].pPortName);
        if (name.rfind("IP_", 0) == 0) name = name.substr(3);
        while (!name.empty() && name.back() == ':') name.pop_back();
        if (ipv4ToUint(name) != 0) hosts.push_back(name);
    }
    return hosts;
}

namespace {

/** One pending non-blocking connect. */
struct PendingConnect {
    SOCKET sock = INVALID_SOCKET;
    std::string host;
    int port = 0;
};

/**
 * Asks a raw-print endpoint for its ESC/POS real-time status.
 *
 * Kept separate from `sendRawTcp` because this must never block a print: it
 * opens its own short-lived socket and gives up quietly.
 */
bool probeEscPosStatus(const std::string& host, int port, int timeoutMs, std::uint8_t& out) {
    SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (sock == INVALID_SOCKET) return false;

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(static_cast<u_short>(port));
    if (InetPtonA(AF_INET, host.c_str(), &addr.sin_addr) != 1) {
        closesocket(sock);
        return false;
    }

    DWORD tv = static_cast<DWORD>(timeoutMs);
    setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, reinterpret_cast<const char*>(&tv), sizeof(tv));
    setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, reinterpret_cast<const char*>(&tv), sizeof(tv));

    if (connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr)) == SOCKET_ERROR) {
        closesocket(sock);
        return false;
    }

    const std::uint8_t query[3] = {0x10, 0x04, 0x01};  // DLE EOT 1
    if (send(sock, reinterpret_cast<const char*>(query), 3, 0) != 3) {
        closesocket(sock);
        return false;
    }

    char reply = 0;
    const int read = recv(sock, &reply, 1, 0);
    closesocket(sock);
    if (read != 1) return false;

    out = static_cast<std::uint8_t>(reply);
    return true;
}

}  // namespace

std::vector<PrinterCandidate> discoverNetworkPrinters(const NetworkScanOptions& options) {
    std::vector<PrinterCandidate> found;

    WSADATA wsa{};
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        logger()->warn("WSAStartup failed, skipping network printer scan");
        return found;
    }

    const auto started = std::chrono::steady_clock::now();
    const auto outOfBudget = [&] {
        const auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
                                 std::chrono::steady_clock::now() - started)
                                 .count();
        return elapsed >= options.budgetMs;
    };

    const std::vector<std::string> hosts = buildScanHostList(options);
    std::vector<std::pair<std::string, int>> open;

    // Non-blocking connect in batches: one select() per batch keeps a /24 sweep
    // of three ports inside a couple of seconds without a thread per host.
    for (int port : options.ports) {
        for (std::size_t offset = 0; offset < hosts.size() && !outOfBudget();
             offset += static_cast<std::size_t>(options.maxConcurrent)) {
            const std::size_t end =
                std::min(hosts.size(), offset + static_cast<std::size_t>(options.maxConcurrent));

            std::vector<PendingConnect> pending;
            pending.reserve(end - offset);

            for (std::size_t i = offset; i < end; ++i) {
                sockaddr_in addr{};
                addr.sin_family = AF_INET;
                addr.sin_port = htons(static_cast<u_short>(port));
                if (InetPtonA(AF_INET, hosts[i].c_str(), &addr.sin_addr) != 1) continue;

                SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
                if (sock == INVALID_SOCKET) continue;

                u_long nonBlocking = 1;
                ioctlsocket(sock, FIONBIO, &nonBlocking);
                connect(sock, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
                pending.push_back({sock, hosts[i], port});
            }
            if (pending.empty()) continue;

            // select() caps out at FD_SETSIZE descriptors per call, so walk the
            // batch in slices of that size rather than assuming it fits.
            for (std::size_t base = 0; base < pending.size(); base += FD_SETSIZE) {
                fd_set writable;
                FD_ZERO(&writable);
                const std::size_t sliceEnd = std::min(pending.size(), base + FD_SETSIZE);
                for (std::size_t i = base; i < sliceEnd; ++i) FD_SET(pending[i].sock, &writable);

                timeval timeout{};
                timeout.tv_sec = options.connectTimeoutMs / 1000;
                timeout.tv_usec = (options.connectTimeoutMs % 1000) * 1000;
                select(0, nullptr, &writable, nullptr, &timeout);

                for (std::size_t i = base; i < sliceEnd; ++i) {
                    if (FD_ISSET(pending[i].sock, &writable)) {
                        open.emplace_back(pending[i].host, pending[i].port);
                    }
                }
            }
            for (auto& p : pending) closesocket(p.sock);
        }
    }

    for (const auto& [host, port] : open) {
        PrinterCandidate candidate;
        candidate.link = PrinterLink::Network;
        candidate.target = "tcp:" + host + ":" + std::to_string(port);
        candidate.ipAddress = host;
        candidate.port = std::to_string(port);
        candidate.macAddress = macForAddress(host);

        std::uint8_t status = 0;
        if (probeEscPosStatus(host, port, options.statusTimeoutMs, status) &&
            isEscPosStatusByte(status)) {
            candidate.escposConfirmed = true;
            candidate.statusByte = status;
            candidate.commandSet = "ESC/POS";
        }

        candidate.displayName = candidate.escposConfirmed
                                    ? "ESC/POS printer " + host
                                    : "Network device " + host + ":" + std::to_string(port);

        // Scored here as well as in rankPrinterCandidates so a caller that uses
        // the sweep on its own still gets a usable ranking.
        candidate.score = scoreCandidate(candidate);

        logger()->info("network printer candidate {}: escpos={} status=0x{:02x} mac={}",
                       candidate.target, candidate.escposConfirmed,
                       static_cast<int>(candidate.statusByte), candidate.macAddress);
        found.push_back(std::move(candidate));
    }

    WSACleanup();
    return found;
}

std::vector<PrinterCandidate> discoverUsbPrinters() {
    std::vector<PrinterCandidate> found;

    HDEVINFO set = SetupDiGetClassDevsW(&kUsbPrintInterface, nullptr, nullptr,
                                        DIGCF_PRESENT | DIGCF_DEVICEINTERFACE);
    if (set == INVALID_HANDLE_VALUE) {
        logger()->warn("SetupDiGetClassDevs(USBPRINT) failed: {}", GetLastError());
        return found;
    }

    SP_DEVICE_INTERFACE_DATA iface{};
    iface.cbSize = sizeof(iface);

    for (DWORD index = 0;
         SetupDiEnumDeviceInterfaces(set, nullptr, &kUsbPrintInterface, index, &iface);
         ++index) {
        DWORD needed = 0;
        SetupDiGetDeviceInterfaceDetailW(set, &iface, nullptr, 0, &needed, nullptr);
        if (needed == 0) continue;

        std::vector<BYTE> buffer(needed, 0);
        auto* detail = reinterpret_cast<PSP_DEVICE_INTERFACE_DETAIL_DATA_W>(buffer.data());
        detail->cbSize = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA_W);

        SP_DEVINFO_DATA info{};
        info.cbSize = sizeof(info);

        if (!SetupDiGetDeviceInterfaceDetailW(set, &iface, detail, needed, nullptr, &info)) {
            continue;
        }

        PrinterCandidate candidate;
        candidate.link = PrinterLink::UsbRaw;
        const std::string devicePath = wideToUtf8(detail->DevicePath);
        candidate.target = "usbraw:" + devicePath;
        candidate.displayName = deviceName(set, info);
        parseUsbIds(devicePath, candidate.vendorId, candidate.productId);

        const DeviceId id = parseDeviceId(queryDeviceId(detail->DevicePath));
        candidate.manufacturer = id.manufacturer;
        candidate.model = id.model;
        candidate.commandSet = id.commandSet;

        if (candidate.displayName.empty()) {
            candidate.displayName = id.model.empty()
                                        ? "USB printer " + candidate.vendorId + ":" +
                                              candidate.productId
                                        : id.manufacturer + " " + id.model;
        }

        found.push_back(std::move(candidate));
    }

    SetupDiDestroyDeviceInfoList(set);
    return found;
}

std::vector<PrinterCandidate> discoverSerialPorts() {
    std::vector<PrinterCandidate> found;

    HDEVINFO set = SetupDiGetClassDevsW(&GUID_DEVCLASS_PORTS, nullptr, nullptr, DIGCF_PRESENT);
    if (set == INVALID_HANDLE_VALUE) return found;

    SP_DEVINFO_DATA info{};
    info.cbSize = sizeof(info);

    for (DWORD index = 0; SetupDiEnumDeviceInfo(set, index, &info); ++index) {
        HKEY key = SetupDiOpenDevRegKey(set, &info, DICS_FLAG_GLOBAL, 0, DIREG_DEV, KEY_READ);
        if (key == nullptr || key == reinterpret_cast<HKEY>(INVALID_HANDLE_VALUE)) continue;

        wchar_t portName[64]{};
        DWORD size = sizeof(portName);
        DWORD type = 0;
        const LSTATUS status = RegQueryValueExW(key, L"PortName", nullptr, &type,
                                                reinterpret_cast<LPBYTE>(portName), &size);
        RegCloseKey(key);
        if (status != ERROR_SUCCESS || type != REG_SZ) continue;

        const std::string port = wideToUtf8(portName);
        if (toLower(port).rfind("com", 0) != 0) continue;  // LPT queues come from the spooler

        PrinterCandidate candidate;
        candidate.link = PrinterLink::Serial;
        candidate.target = "serial:" + port;
        candidate.port = port;
        candidate.displayName = deviceName(set, info);
        if (candidate.displayName.empty()) candidate.displayName = port;
        found.push_back(std::move(candidate));
    }

    SetupDiDestroyDeviceInfoList(set);
    return found;
}

std::vector<PrinterCandidate> discoverSpoolerQueues() {
    std::vector<PrinterCandidate> found;

    DWORD needed = 0;
    DWORD returned = 0;
    EnumPrintersW(PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS, nullptr, 2, nullptr, 0, &needed,
                  &returned);
    if (needed == 0) return found;

    std::vector<BYTE> buffer(needed);
    if (!EnumPrintersW(PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS, nullptr, 2, buffer.data(),
                       needed, &needed, &returned)) {
        return found;
    }

    auto* info = reinterpret_cast<PRINTER_INFO_2W*>(buffer.data());
    for (DWORD i = 0; i < returned; ++i) {
        if (!info[i].pPrinterName) continue;

        const std::string name = wideToUtf8(info[i].pPrinterName);
        const std::string port = wideToUtf8(info[i].pPortName);
        const std::string driver = wideToUtf8(info[i].pDriverName);
        if (name.empty() || isSoftwarePrinter(name, port, driver)) continue;

        const auto lowerPort = toLower(port);
        PrinterCandidate candidate;
        candidate.displayName = name;
        candidate.target = "win:" + name;
        candidate.port = port;
        candidate.driver = driver;

        if (contains(lowerPort, "usb")) candidate.link = PrinterLink::UsbQueue;
        else if (lowerPort.rfind("com", 0) == 0) candidate.link = PrinterLink::Serial;
        else if (lowerPort.rfind("lpt", 0) == 0) candidate.link = PrinterLink::Lpt;
        else if (contains(lowerPort, "tcp") || lowerPort.rfind("wsd", 0) == 0)
            candidate.link = PrinterLink::Network;
        else candidate.link = PrinterLink::Other;

        found.push_back(std::move(candidate));
    }

    return found;
}

#else  // !_WIN32

// The sidecar only ever runs on the till, but the pure helpers above are unit
// tested on any host, so the platform calls need non-Windows definitions.
std::vector<PrinterCandidate> discoverUsbPrinters() { return {}; }
std::vector<PrinterCandidate> discoverSerialPorts() { return {}; }
std::vector<PrinterCandidate> discoverSpoolerQueues() { return {}; }
std::vector<std::pair<std::uint32_t, int>> localScanSubnets() { return {}; }
std::vector<std::string> arpCacheHosts() { return {}; }
std::string macForAddress(std::string_view) { return {}; }
std::vector<std::string> printerPortHosts() { return {}; }
std::vector<PrinterCandidate> discoverNetworkPrinters(const NetworkScanOptions&) { return {}; }

#endif  // _WIN32

std::vector<PrinterCandidate> rankPrinterCandidates(const std::string& currentTarget,
                                                    bool includeNetwork) {
    std::vector<PrinterCandidate> all = discoverUsbPrinters();

    for (auto& candidate : discoverSerialPorts()) all.push_back(std::move(candidate));
    for (auto& candidate : discoverSpoolerQueues()) all.push_back(std::move(candidate));

    if (includeNetwork) {
        NetworkScanOptions options;
        if (!currentTarget.empty() && currentTarget != "auto" && currentTarget != "virtual") {
            options.knownTargets.push_back(currentTarget);
        }
        for (auto& candidate : discoverNetworkPrinters(options)) all.push_back(std::move(candidate));
    }

    // A USB device reachable both raw and through a spooler queue is one
    // printer, not two. Keep the raw entry - it works without a driver - but
    // fold the queue's driver name into it so the operator recognises it.
    for (auto& candidate : all) {
        if (candidate.link != PrinterLink::UsbQueue) continue;
        for (auto& raw : all) {
            if (raw.link != PrinterLink::UsbRaw) continue;
            if (raw.driver.empty() && toLower(raw.displayName) == toLower(candidate.displayName)) {
                raw.driver = candidate.driver;
                raw.port = candidate.port;
            }
        }
    }

    PrinterCandidate virtualTarget;
    virtualTarget.target = "virtual";
    virtualTarget.displayName = "Virtual printer (fayla yazır)";
    virtualTarget.link = PrinterLink::Virtual;
    all.push_back(virtualTarget);

    const bool haveCurrent =
        currentTarget.empty() || currentTarget == "auto" ||
        std::any_of(all.begin(), all.end(),
                    [&](const PrinterCandidate& c) { return c.target == currentTarget; });

    if (!haveCurrent) {
        PrinterCandidate configured;
        configured.target = currentTarget;
        configured.displayName = currentTarget;
        configured.link = currentTarget.rfind("tcp:", 0) == 0 ? PrinterLink::Network
                                                              : PrinterLink::Other;
        all.push_back(configured);
    }

    for (auto& candidate : all) {
        candidate.isCurrent = !currentTarget.empty() && candidate.target == currentTarget;
        candidate.score = scoreCandidate(candidate);
    }

    std::stable_sort(all.begin(), all.end(),
                     [](const PrinterCandidate& a, const PrinterCandidate& b) {
                         return a.score > b.score;
                     });
    return all;
}

}  // namespace market::printing
